// Generated by XXML Compiler

#include <iostream>
#include <string>
#include <memory>
#include <cstdint>
#include <cstring>
#include <limits>
#include <cassert>
#include <stdexcept>
#include <utility>

// ============================================
// Owned<T> - Runtime wrapper for owned values (T^)
// ============================================
namespace Language {
namespace Runtime {

template<typename T>
class Owned {
private:
    T value_;
    bool movedFrom_;

public:
    Owned() : value_(), movedFrom_(false) {}  // Default constructor
    Owned(const T& val) : value_(val), movedFrom_(false) {}  // Copy for primitives
    Owned(T&& val) : value_(std::move(val)), movedFrom_(false) {}  // Move

    Owned(const Owned&) = delete;
    Owned& operator=(const Owned&) = delete;

    Owned(Owned&& other) noexcept
        : value_(std::move(other.value_)), movedFrom_(false) {
        other.movedFrom_ = true;
    }

    Owned& operator=(Owned&& other) noexcept {
        if (this != &other) {
            value_ = std::move(other.value_);
            movedFrom_ = false;
            other.movedFrom_ = true;
        }
        return *this;
    }

    T& get() {
        if (movedFrom_) {
            assert(false && "Use-after-move detected");
            throw std::runtime_error("Use-after-move detected");
        }
        return value_;
    }

    const T& get() const {
        if (movedFrom_) {
            assert(false && "Use-after-move detected");
            throw std::runtime_error("Use-after-move detected");
        }
        return value_;
    }

    T extract() {
        if (movedFrom_) {
            assert(false && "Use-after-move detected");
            throw std::runtime_error("Use-after-move detected");
        }
        movedFrom_ = true;
        return std::move(value_);
    }

    operator T&() { return get(); }
    operator const T&() const { return get(); }
    T* operator->() { return &get(); }
    const T* operator->() const { return &get(); }
    bool isMovedFrom() const { return movedFrom_; }
};

} // namespace Runtime
} // namespace Language

// Syscall intrinsic functions
class Syscall {
public:
    static void* string_create(const void* cstr) {
        return (void*)new std::string((const char*)cstr);
    }
    static const char* string_cstr(void* ptr) {
        return ((std::string*)ptr)->c_str();
    }
    static int64_t string_length(void* ptr) {
        return ((std::string*)ptr)->length();
    }
    static void* string_concat(void* ptr1, void* ptr2) {
        std::string* s1 = (std::string*)ptr1;
        std::string* s2 = (std::string*)ptr2;
        return (void*)new std::string(*s1 + *s2);
    }
    static void* string_copy(void* ptr) {
        return (void*)new std::string(*(std::string*)ptr);
    }
    static int64_t string_equals(void* ptr1, void* ptr2) {
        return (*(std::string*)ptr1 == *(std::string*)ptr2) ? 1 : 0;
    }
    static void string_destroy(void* ptr) {
        delete (std::string*)ptr;
    }
    static void memcpy(void* dest, const void* src, size_t n) {
        std::memcpy(dest, src, n);
    }
};

// StringArray stub
class StringArray {
public:
    StringArray() {}
    static StringArray Constructor() { return StringArray(); }
};

// System::Console intrinsic class (will be implemented after core types)
namespace System {
class Console;
} // namespace System

// Forward declarations
namespace Language::Core {
    class Bool;
    class Integer;
    class Float;
    class Double;
    class String;
}
namespace System {
    class Console;
}

// ============================================
// Core Library - Class Declarations
// ============================================

namespace Language::Core {

    class Integer {
        private:
            Language::Runtime::Owned<int64_t> value;
        public:
            Integer() = default;
            Integer(int64_t val) : value(val) {}
            static Integer Constructor(int64_t val) { return Integer(val); }
            int64_t toInt64();
            Language::Runtime::Owned<Language::Core::Integer> add(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Integer> subtract(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Integer> multiply(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Integer> divide(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Integer> modulo(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Bool> equals(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Bool> lessThan(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Bool> greaterThan(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Bool> lessOrEqual(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Bool> greaterOrEqual(Language::Core::Integer& other);
            Language::Runtime::Owned<Language::Core::Integer> negate();
            Language::Runtime::Owned<Language::Core::Integer> abs();
    };
    
} // namespace Language::Core

namespace Language::Core {

    class Bool {
        private:
            Language::Runtime::Owned<bool> value;
        public:
            Bool() = default;
            Bool(bool val) : value(val) {}
            static Bool Constructor(bool val) { return Bool(val); }
            bool toBool();
            Language::Runtime::Owned<Language::Core::Bool> and_(Language::Core::Bool& other);
            Language::Runtime::Owned<Language::Core::Bool> or_(Language::Core::Bool& other);
            Language::Runtime::Owned<Language::Core::Bool> not_();
            Language::Runtime::Owned<Language::Core::Bool> xor_(Language::Core::Bool& other);
            Language::Runtime::Owned<Language::Core::Bool> equals(Language::Core::Bool& other);
            Language::Runtime::Owned<Language::Core::Integer> toInteger();
    };
    
} // namespace Language::Core

namespace Language::Core {

    class Float {
        private:
            Language::Runtime::Owned<float> value;
        public:
            Float() = default;
            Float(float val) : value(val) {}
            static Float Constructor(float val) { return Float(val); }
            float toFloat();
            Language::Runtime::Owned<Language::Core::Float> add(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Float> subtract(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Float> multiply(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Float> divide(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Bool> equals(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Bool> lessThan(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Bool> greaterThan(Language::Core::Float& other);
            Language::Runtime::Owned<Language::Core::Float> negate();
            Language::Runtime::Owned<Language::Core::Float> abs();
            Language::Runtime::Owned<Language::Core::Integer> toInteger();
            Language::Core::Double toDouble();
    };
    
} // namespace Language::Core

namespace Language::Core {

    class Double {
        private:
            Language::Runtime::Owned<double> value;
        public:
            Double() = default;
            Double(double val) : value(val) {}
            static Double Constructor(double val) { return Double(val); }
            double toDouble();
            Language::Runtime::Owned<Language::Core::Double> add(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Double> subtract(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Double> multiply(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Double> divide(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Bool> equals(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Bool> lessThan(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Bool> greaterThan(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Bool> lessOrEqual(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Bool> greaterOrEqual(Language::Core::Double& other);
            Language::Runtime::Owned<Language::Core::Double> negate();
            Language::Runtime::Owned<Language::Core::Double> abs();
            Language::Runtime::Owned<Language::Core::Integer> toInteger();
            Language::Core::Float toFloat();
    };
    
} // namespace Language::Core

namespace Language::Core {

    class String {
        private:
            Language::Runtime::Owned<void*> data;
        public:
            String() = default;
            String(const void* cstr) {
                Language::Runtime::Owned<void*> ptr = Syscall::string_create(cstr);
                Syscall::memcpy(&data, &ptr, 8);
            }
            static String Constructor(const void* cstr) { return String(cstr); }
            const void* toCString();
            Language::Runtime::Owned<Language::Core::Integer> length();
            Language::Runtime::Owned<Language::Core::Bool> isEmpty();
            Language::Runtime::Owned<Language::Core::String> append(Language::Core::String& other);
            Language::Runtime::Owned<Language::Core::String> copy();
            Language::Runtime::Owned<Language::Core::Bool> equals(Language::Core::String& other);
            void dispose();
    };
    
} // namespace Language::Core

// ============================================
// Core Library - Method Implementations
// ============================================

namespace Language::Core {

        int64_t Language::Core::Integer::toInt64() {
        return value;
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::add(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        Language::Runtime::Owned<int64_t> result = v1 + v2;
        return Language::Core::Integer(result);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::subtract(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        Language::Runtime::Owned<int64_t> result = v1 - v2;
        return Language::Core::Integer(result);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::multiply(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        Language::Runtime::Owned<int64_t> result = v1 * v2;
        return Language::Core::Integer(result);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::divide(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        Language::Runtime::Owned<int64_t> result = v1 / v2;
        return Language::Core::Integer(result);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::modulo(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        Language::Runtime::Owned<int64_t> result = v1 % v2;
        return Language::Core::Integer(result);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Integer::equals(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        if (v1 == v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Integer::lessThan(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        if (v1 < v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Integer::greaterThan(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        if (v1 > v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Integer::lessOrEqual(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        if (v1 <= v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Integer::greaterOrEqual(Language::Core::Integer& other) {
        Language::Runtime::Owned<int64_t> v1(value.get());
        Language::Runtime::Owned<int64_t> v2(other.value.get());
        if (v1 >= v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::negate() {
        Language::Runtime::Owned<int64_t> v(value.get());
        Language::Runtime::Owned<int64_t> result = 0 - v;
        return Language::Core::Integer(result);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Integer::abs() {
        Language::Runtime::Owned<int64_t> v(value.get());
        if (v < 0) {
            Language::Runtime::Owned<int64_t> result = 0 - v;
            return Language::Core::Integer(result);
        }
        return Language::Core::Integer(v);
    }
} // namespace Language::Core

namespace Language::Core {

        bool Language::Core::Bool::toBool() {
        return value;
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Bool::and_(Language::Core::Bool& other) {
        Language::Runtime::Owned<bool> v1(value.get());
        Language::Runtime::Owned<bool> v2(other.value.get());
        Language::Runtime::Owned<bool> result = v1 && v2;
        return Language::Core::Bool(result);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Bool::or_(Language::Core::Bool& other) {
        Language::Runtime::Owned<bool> v1(value.get());
        Language::Runtime::Owned<bool> v2(other.value.get());
        Language::Runtime::Owned<bool> result = v1 || v2;
        return Language::Core::Bool(result);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Bool::not_() {
        Language::Runtime::Owned<bool> v(value.get());
        Language::Runtime::Owned<bool> result = !v;
        return Language::Core::Bool(result);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Bool::xor_(Language::Core::Bool& other) {
        Language::Runtime::Owned<bool> v1(value.get());
        Language::Runtime::Owned<bool> v2(other.value.get());
        if (v1 == v2) {
            return Language::Core::Bool(false);
        }
        return Language::Core::Bool(true);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Bool::equals(Language::Core::Bool& other) {
        Language::Runtime::Owned<bool> v1(value.get());
        Language::Runtime::Owned<bool> v2(other.value.get());
        if (v1 == v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Bool::toInteger() {
        Language::Runtime::Owned<bool> v(value.get());
        if (v == true) {
            return Language::Core::Integer(1);
        }
        return Language::Core::Integer(0);
    }
} // namespace Language::Core

namespace Language::Core {

        float Language::Core::Float::toFloat() {
        return value;
    }
    Language::Runtime::Owned<Language::Core::Float> Language::Core::Float::add(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        Language::Runtime::Owned<float> result = v1 + v2;
        return Language::Core::Float(result);
    }
    Language::Runtime::Owned<Language::Core::Float> Language::Core::Float::subtract(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        Language::Runtime::Owned<float> result = v1 - v2;
        return Language::Core::Float(result);
    }
    Language::Runtime::Owned<Language::Core::Float> Language::Core::Float::multiply(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        Language::Runtime::Owned<float> result = v1 * v2;
        return Language::Core::Float(result);
    }
    Language::Runtime::Owned<Language::Core::Float> Language::Core::Float::divide(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        Language::Runtime::Owned<float> result = v1 / v2;
        return Language::Core::Float(result);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Float::equals(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        if (v1 == v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Float::lessThan(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        if (v1 < v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Float::greaterThan(Language::Core::Float& other) {
        Language::Runtime::Owned<float> v1(value.get());
        Language::Runtime::Owned<float> v2(other.value.get());
        if (v1 > v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Float> Language::Core::Float::negate() {
        Language::Runtime::Owned<float> v(value.get());
        Language::Runtime::Owned<float> zero = 0;
        Language::Runtime::Owned<float> result = zero - v;
        return Language::Core::Float(result);
    }
    Language::Runtime::Owned<Language::Core::Float> Language::Core::Float::abs() {
        Language::Runtime::Owned<float> v(value.get());
        Language::Runtime::Owned<float> zero = 0;
        if (v < zero) {
            Language::Runtime::Owned<float> result = zero - v;
            return Language::Core::Float(result);
        }
        return Language::Core::Float(v);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Float::toInteger() {
        Language::Runtime::Owned<float> v(value.get());
        Language::Runtime::Owned<int64_t> result(v.get());
        return Language::Core::Integer(result);
    }
    Language::Core::Double Language::Core::Float::toDouble() {
        Language::Runtime::Owned<float> v(value.get());
        Language::Runtime::Owned<double> result(v.get());
        return Language::Core::Double(result);
    }
} // namespace Language::Core

namespace Language::Core {

        double Language::Core::Double::toDouble() {
        return value;
    }
    Language::Runtime::Owned<Language::Core::Double> Language::Core::Double::add(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        Language::Runtime::Owned<double> result = v1 + v2;
        return Language::Core::Double(result);
    }
    Language::Runtime::Owned<Language::Core::Double> Language::Core::Double::subtract(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        Language::Runtime::Owned<double> result = v1 - v2;
        return Language::Core::Double(result);
    }
    Language::Runtime::Owned<Language::Core::Double> Language::Core::Double::multiply(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        Language::Runtime::Owned<double> result = v1 * v2;
        return Language::Core::Double(result);
    }
    Language::Runtime::Owned<Language::Core::Double> Language::Core::Double::divide(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        Language::Runtime::Owned<double> result = v1 / v2;
        return Language::Core::Double(result);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Double::equals(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        if (v1 == v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Double::lessThan(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        if (v1 < v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Double::greaterThan(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        if (v1 > v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Double::lessOrEqual(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        if (v1 <= v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::Double::greaterOrEqual(Language::Core::Double& other) {
        Language::Runtime::Owned<double> v1(value.get());
        Language::Runtime::Owned<double> v2(other.value.get());
        if (v1 >= v2) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::Double> Language::Core::Double::negate() {
        Language::Runtime::Owned<double> v(value.get());
        Language::Runtime::Owned<double> zero = 0;
        Language::Runtime::Owned<double> result = zero - v;
        return Language::Core::Double(result);
    }
    Language::Runtime::Owned<Language::Core::Double> Language::Core::Double::abs() {
        Language::Runtime::Owned<double> v(value.get());
        Language::Runtime::Owned<double> zero = 0;
        if (v < zero) {
            Language::Runtime::Owned<double> result = zero - v;
            return Language::Core::Double(result);
        }
        return Language::Core::Double(v);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::Double::toInteger() {
        Language::Runtime::Owned<double> v(value.get());
        Language::Runtime::Owned<int64_t> result(v.get());
        return Language::Core::Integer(result);
    }
    Language::Core::Float Language::Core::Double::toFloat() {
        Language::Runtime::Owned<double> v(value.get());
        Language::Runtime::Owned<float> result(v.get());
        return Language::Core::Float(result);
    }
} // namespace Language::Core

namespace Language::Core {

        const void* Language::Core::String::toCString() {
        Language::Runtime::Owned<void*> ptr(data.get());
        return Syscall::string_cstr(ptr);
    }
    Language::Runtime::Owned<Language::Core::Integer> Language::Core::String::length() {
        Language::Runtime::Owned<void*> ptr(data.get());
        Language::Runtime::Owned<int64_t> len = Syscall::string_length(ptr);
        return Language::Core::Integer(len);
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::String::isEmpty() {
        Language::Runtime::Owned<void*> ptr(data.get());
        Language::Runtime::Owned<int64_t> len = Syscall::string_length(ptr);
        if (len == 0) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    Language::Runtime::Owned<Language::Core::String> Language::Core::String::append(Language::Core::String& other) {
        Language::Runtime::Owned<void*> ptr1(data.get());
        Language::Runtime::Owned<void*> ptr2(other.data.get());
        Language::Runtime::Owned<void*> newPtr = Syscall::string_concat(ptr1, ptr2);
        Syscall::memcpy(&data, &newPtr, 8);
        return std::move(*this);
    }
    Language::Runtime::Owned<Language::Core::String> Language::Core::String::copy() {
        Language::Runtime::Owned<const void*> empty = "";
        Language::Runtime::Owned<Language::Core::String> result = Language::Core::String(empty);
        Language::Runtime::Owned<void*> ptr(data.get());
        Language::Runtime::Owned<void*> newPtr = Syscall::string_copy(ptr);
        Syscall::memcpy(&result->data, &newPtr, 8);
        return result;
    }
    Language::Runtime::Owned<Language::Core::Bool> Language::Core::String::equals(Language::Core::String& other) {
        Language::Runtime::Owned<void*> ptr1(data.get());
        Language::Runtime::Owned<void*> ptr2(other.data.get());
        Language::Runtime::Owned<int64_t> result = Syscall::string_equals(ptr1, ptr2);
        if (result == 1) {
            return Language::Core::Bool(true);
        }
        return Language::Core::Bool(false);
    }
    void Language::Core::String::dispose() {
        Language::Runtime::Owned<void*> ptr(data.get());
        if (ptr != 0) {
            Syscall::string_destroy(ptr);
            Language::Runtime::Owned<void*> zero = 0;
            Syscall::memcpy(&data, &zero, 8);
        }
    }
} // namespace Language::Core

// ============================================
// System::Console Implementation
// ============================================
namespace System {
class Console {
public:
    // Print without newline - takes Language::Core::String
    static void print(Language::Core::String str) {
        const char* cstr = (const char*)str.toCString();
        std::cout << cstr;
        std::cout.flush();
    }

    // Print with newline - takes Language::Core::String
    static void printLine(Language::Core::String str) {
        const char* cstr = (const char*)str.toCString();
        std::cout << cstr << std::endl;
    }

    // Read a line from stdin - returns string pointer
    static void* readLine() {
        std::string* line = new std::string();
        std::getline(std::cin, *line);
        return (void*)line;
    }

    // Read a single character - returns string pointer
    static void* readChar() {
        std::string* ch = new std::string();
        char c;
        if (std::cin.get(c)) {
            *ch = c;
        }
        return (void*)ch;
    }

    // Read an integer - returns int64_t
    static int64_t readInt() {
        int64_t value = 0;
        std::cin >> value;
        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        return value;
    }
};
} // namespace System

// ============================================
// Language::Core::Mem Implementation
// ============================================
namespace Language {
namespace Core {
namespace Mem {

    // Move operation - transfers ownership from Owned<T>
    template<typename T>
    Language::Runtime::Owned<T> move(Language::Runtime::Owned<T>& owned) {
        T extracted = owned.extract();
        return Language::Runtime::Owned<T>(std::move(extracted));
    }

} // namespace Mem
} // namespace Core
} // namespace Language

// ============================================
// Module: __main__
// ============================================
int main() {
    using namespace Language::Core;
    
    System::Console::printLine(Language::Core::String("=== XXML COMPREHENSIVE TEST SUITE ==="));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 1: Integer Operations ---"));
    Language::Runtime::Owned<Language::Core::Integer> num1 = Language::Core::Integer(42);
    Language::Runtime::Owned<Language::Core::Integer> num2 = Language::Core::Integer(10);
    Language::Runtime::Owned<Language::Core::Integer> sum = num1->add(num2);
    Language::Runtime::Owned<Language::Core::Integer> diff = num1->subtract(num2);
    Language::Runtime::Owned<Language::Core::Integer> product = num1->multiply(num2);
    Language::Runtime::Owned<Language::Core::Integer> quotient = num1->divide(num2);
    System::Console::printLine(Language::Core::String("Integer arithmetic: 42+10, 42-10, 42*10, 42/10"));
    Language::Runtime::Owned<Language::Core::Bool> isEqual = num1->equals(num2);
    Language::Runtime::Owned<Language::Core::Bool> isLess = num2->lessThan(num1);
    Language::Runtime::Owned<Language::Core::Bool> isGreater = num1->greaterThan(num2);
    Language::Runtime::Owned<Language::Core::Bool> isLessEq = num2->lessOrEqual(num1);
    Language::Runtime::Owned<Language::Core::Bool> isGreaterEq = num1->greaterOrEqual(num2);
    System::Console::printLine(Language::Core::String("Integer comparisons: equals, <, >, <=, >="));
    System::Console::printLine(Language::Core::String("✓ PASSED: Integer Operations"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 2: Boolean Operations ---"));
    Language::Runtime::Owned<Language::Core::Bool> flag1 = Language::Core::Bool(true);
    Language::Runtime::Owned<Language::Core::Bool> flag2 = Language::Core::Bool(false);
    Language::Runtime::Owned<Language::Core::Bool> andResult = flag1->and_(flag2);
    Language::Runtime::Owned<Language::Core::Bool> orResult = flag1->or_(flag2);
    Language::Runtime::Owned<Language::Core::Bool> notResult = flag1->not_();
    Language::Runtime::Owned<Language::Core::Bool> xorResult = flag1->xor_(flag2);
    System::Console::printLine(Language::Core::String("Boolean logic: AND, OR, NOT, XOR"));
    System::Console::printLine(Language::Core::String("✓ PASSED: Boolean Operations"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 3: String Operations ---"));
    Language::Runtime::Owned<Language::Core::String> str1 = Language::Core::String("Hello");
    Language::Runtime::Owned<Language::Core::String> str2 = Language::Core::String(" World");
    Language::Runtime::Owned<Language::Core::String> combined = str1->append(str2);
    Language::Runtime::Owned<Language::Core::Integer> strLen = combined->length();
    Language::Runtime::Owned<Language::Core::Bool> isEmpty = combined->isEmpty();
    Language::Runtime::Owned<Language::Core::Bool> strEquals = str1->equals(str2);
    System::Console::printLine(Language::Core::String("String ops: append, length, isEmpty, equals"));
    Language::Runtime::Owned<Language::Core::String> copy = combined->copy();
    Language::Runtime::Owned<Language::Core::Bool> copyEquals = combined->equals(copy);
    System::Console::printLine(Language::Core::String("String copy and comparison completed"));
    System::Console::printLine(Language::Core::String("✓ PASSED: String Operations"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 4: If Statements ---"));
    Language::Runtime::Owned<Language::Core::Integer> testVal = Language::Core::Integer(50);
    Language::Runtime::Owned<Language::Core::Integer> threshold = Language::Core::Integer(25);
    Language::Runtime::Owned<Language::Core::Bool> condition = testVal->greaterThan(threshold);
    if (condition) {
        System::Console::printLine(Language::Core::String("If condition evaluated: 50 > 25 is TRUE"));
    }
    System::Console::printLine(Language::Core::String("✓ PASSED: If Statements"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 5: While Loops ---"));
    Language::Runtime::Owned<Language::Core::Integer> counter = Language::Core::Integer(0);
    Language::Runtime::Owned<Language::Core::Integer> loopLimit = Language::Core::Integer(5);
    Language::Runtime::Owned<Language::Core::Integer> one = Language::Core::Integer(1);
    while (counter->lessThan(loopLimit)) {
        counter->add(one);
    }
    System::Console::printLine(Language::Core::String("While loop: counted from 0 to 5"));
    System::Console::printLine(Language::Core::String("✓ PASSED: While Loops"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 6: Ownership (^, &) ---"));
    Language::Runtime::Owned<Language::Core::Integer> owned1 = Language::Core::Integer(100);
    Language::Runtime::Owned<Language::Core::Integer> owned2 = Language::Core::Integer(200);
    System::Console::printLine(Language::Core::String("Created owned values: 100, 200"));
    Language::Runtime::Owned<Language::Core::Bool> compareResult = owned1->equals(owned2);
    System::Console::printLine(Language::Core::String("Borrowed comparison (no move)"));
    System::Console::printLine(Language::Core::String("✓ PASSED: Ownership"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 7: Edge Cases ---"));
    Language::Runtime::Owned<Language::Core::Integer> zero = Language::Core::Integer(0);
    Language::Runtime::Owned<Language::Core::Integer> anyNum = Language::Core::Integer(42);
    Language::Runtime::Owned<Language::Core::Integer> zeroSum = zero->add(anyNum);
    System::Console::printLine(Language::Core::String("Zero arithmetic: 0 + 42 = 42"));
    Language::Runtime::Owned<Language::Core::Integer> negative = Language::Core::Integer(-42);
    Language::Runtime::Owned<Language::Core::Integer> negSum = negative->add(anyNum);
    System::Console::printLine(Language::Core::String("Negative values: -42 + 42 = 0"));
    Language::Runtime::Owned<Language::Core::String> emptyStr = Language::Core::String("");
    Language::Runtime::Owned<Language::Core::Bool> isEmptyStr = emptyStr->isEmpty();
    Language::Runtime::Owned<Language::Core::Integer> emptyLen = emptyStr->length();
    System::Console::printLine(Language::Core::String("Empty string: isEmpty() and length()"));
    System::Console::printLine(Language::Core::String("✓ PASSED: Edge Cases"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("--- Test 8: Nested Operations ---"));
    Language::Runtime::Owned<Language::Core::Integer> n1 = Language::Core::Integer(10);
    Language::Runtime::Owned<Language::Core::Integer> n2 = Language::Core::Integer(20);
    Language::Runtime::Owned<Language::Core::Integer> n3 = Language::Core::Integer(2);
    Language::Runtime::Owned<Language::Core::Integer> nSum = n1->add(n2);
    Language::Runtime::Owned<Language::Core::Integer> nResult = nSum->multiply(n3);
    System::Console::printLine(Language::Core::String("Nested arithmetic: (10 + 20) * 2 = 60"));
    Language::Runtime::Owned<Language::Core::Integer> na = Language::Core::Integer(5);
    Language::Runtime::Owned<Language::Core::Integer> nb = Language::Core::Integer(15);
    Language::Runtime::Owned<Language::Core::Integer> nc = Language::Core::Integer(25);
    Language::Runtime::Owned<Language::Core::Bool> cmp1 = na->lessThan(nb);
    Language::Runtime::Owned<Language::Core::Bool> cmp2 = nb->lessThan(nc);
    Language::Runtime::Owned<Language::Core::Bool> cmpRes = cmp1->and_(cmp2);
    System::Console::printLine(Language::Core::String("Nested comparisons: (5<15) AND (15<25)"));
    Language::Runtime::Owned<Language::Core::String> s1 = Language::Core::String("A");
    Language::Runtime::Owned<Language::Core::String> s2 = Language::Core::String("B");
    Language::Runtime::Owned<Language::Core::String> s3 = Language::Core::String("C");
    Language::Runtime::Owned<Language::Core::String> s12 = s1->append(s2);
    Language::Runtime::Owned<Language::Core::String> s123 = s12->append(s3);
    System::Console::printLine(Language::Core::String("Nested strings: A + B + C = ABC"));
    System::Console::printLine(Language::Core::String("✓ PASSED: Nested Operations"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("╔════════════════════════════════════════════════╗"));
    System::Console::printLine(Language::Core::String("║                                                ║"));
    System::Console::printLine(Language::Core::String("║    ALL COMPREHENSIVE TESTS PASSED! ✓✓✓        ║"));
    System::Console::printLine(Language::Core::String("║                                                ║"));
    System::Console::printLine(Language::Core::String("╚════════════════════════════════════════════════╝"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("Complete Feature Coverage:"));
    System::Console::printLine(Language::Core::String("  ✓ Integer (arithmetic, comparisons)"));
    System::Console::printLine(Language::Core::String("  ✓ Boolean (AND, OR, NOT, XOR)"));
    System::Console::printLine(Language::Core::String("  ✓ String (append, length, copy, equals)"));
    System::Console::printLine(Language::Core::String("  ✓ If statements"));
    System::Console::printLine(Language::Core::String("  ✓ While loops"));
    System::Console::printLine(Language::Core::String("  ✓ Ownership semantics (^, &)"));
    System::Console::printLine(Language::Core::String("  ✓ Edge cases (zero, negative, empty)"));
    System::Console::printLine(Language::Core::String("  ✓ Nested operations"));
    System::Console::printLine(Language::Core::String(""));
    System::Console::printLine(Language::Core::String("Language Features Tested:"));
    System::Console::printLine(Language::Core::String("  - Classes and Methods"));
    System::Console::printLine(Language::Core::String("  - Static Methods (Constructor)"));
    System::Console::printLine(Language::Core::String("  - Ownership Qualifiers (Owned ^, Borrow &)"));
    System::Console::printLine(Language::Core::String("  - Control Flow (If, While)"));
    System::Console::printLine(Language::Core::String("  - Method Chaining"));
    System::Console::printLine(Language::Core::String("  - Namespaces (System::Console)"));
    System::Console::printLine(Language::Core::String(""));
}



