// Generated by XXML Compiler
// Do not edit this file manually

#include "runtime/xxml_runtime.h"
#include <iostream>
#include <string>
#include <memory>
#include <cstdint>

// Import: Language::Core
// Import: System
// Import: String
namespace TestSuite::Core {

    class Animal {
        private:
            String name;
            Integer age;
        public:
            Animal() = default;
            void setName(String& newName) {
                Copy(name);
            }
            String getName() {
                return Copy(name);
            }
            Integer getAge() {
                return age;
            }
    };
    
    class Dog : public Animal {
        private:
            String breed;
        public:
            Dog() = default;
            void bark(Integer times, String& message) {
                for (Integer i = Integer(0); i < times; i++) {
                    System::Print(Append(Copy(message), String::Convert(i)));
                }
            }
    };
    
} // namespace TestSuite::Core

namespace TestSuite::Math {

    class Calculator {
        public:
            Integer lastResult;
            Calculator() = default;
            Integer add(Integer a, Integer b) {
                return a + b;
            }
            Integer subtract(Integer a, Integer b) {
                return a - b;
            }
            Integer multiply(Integer a, Integer b) {
                return a * b;
            }
            Integer divide(Integer a, Integer b) {
                return a / b;
            }
            Integer modulo(Integer a, Integer b) {
                return a % b;
            }
    };
    
    class ComplexCalculator : public Calculator {
        public:
            Integer getPi() {
                return Integer(314);
            }
            Integer square(Integer x) {
                return x * x;
            }
            void demonstrateOperators(Integer x, Integer y) {
                Integer sum = x + y;
                Integer diff = x - y;
                Integer product = x * y;
                Integer quotient = x / y;
                Integer remainder = x % y;
                System::Print(String::Convert(sum));
                System::Print(String::Convert(diff));
                System::Print(String::Convert(product));
                System::Print(String::Convert(quotient));
                System::Print(String::Convert(remainder));
            }
    };
    
} // namespace TestSuite::Math

namespace TestSuite::Text {

    class StringManipulator {
        private:
            String buffer;
        public:
            StringManipulator() = default;
            String process(String& input) {
                return Append(Copy(input), String(String(" processed")));
            }
            void appendTo(String& target, String& suffix) {
                Append(target, suffix);
            }
            void store(String data) {
            }
    };
    
} // namespace TestSuite::Text

namespace TestSuite::Collection {

    class Counter {
        private:
            Integer count;
        protected:
            Integer maxCount;
        public:
            Counter() = default;
            void increment() {
            }
            void decrement() {
            }
            void reset() {
            }
            Integer getValue() {
                return count;
            }
    };
    
    class BoundedCounter : public Counter {
        public:
            void incrementSafe() {
            }
    };
    
} // namespace TestSuite::Collection

namespace TestSuite::Final {

    class SealedClass {
        public:
            Integer data;
            SealedClass() = default;
    };
    
} // namespace TestSuite::Final

namespace TestSuite::Ownership {

    class OwnershipDemo {
        public:
            String ownedString;
            String& refString;
            OwnershipDemo() = default;
            String processData(String owned, String& referenced, const String& copied) {
                return Copy(owned);
            }
            void demonstrateOwnership() {
                String owned = String(String("owned"));
                System::Print(owned);
                String copied = String(String("copied"));
            }
    };
    
} // namespace TestSuite::Ownership

int main() {
    std::unique_ptr<TestSuite::Math::Calculator> calc = std::make_unique<TestSuite::Math::Calculator>();
    Integer x = Integer(10);
    Integer y = Integer(5);
    Integer sum = calc->add(x, y);
    Integer difference = calc->subtract(x, y);
    Integer product = calc->multiply(x, y);
    Integer quotient = calc->divide(x, y);
    Integer mod = calc->modulo(x, y);
    System::Print(String::Convert(sum));
    System::Print(String::Convert(difference));
    System::Print(String::Convert(product));
    System::Print(String::Convert(quotient));
    System::Print(String::Convert(mod));
    String message1 = String(String("Hello"));
    String message2 = String(String(" World"));
    System::Print(message1);
    String combined = Append(Copy(message1), message2);
    System::Print(combined);
    System::Print(String(String("Counting 0 to 5:")));
    for (Integer i = Integer(0); i < Integer(5); i++) {
        System::Print(String::Convert(i));
    }
    System::Print(String(String("Counting 10 to 15:")));
    for (Integer j = Integer(10); j < Integer(15); j++) {
        System::Print(String::Convert(j));
    }
    std::unique_ptr<TestSuite::Core::Dog> myDog = std::make_unique<TestSuite::Core::Dog>();
    String barkSound = String(String("Woof! "));
    myDog->bark(Integer(3), barkSound);
    std::unique_ptr<TestSuite::Text::StringManipulator> stringManip = std::make_unique<TestSuite::Text::StringManipulator>();
    String original = String(String("Original"));
    String processed = stringManip->process(original);
    System::Print(processed);
    std::unique_ptr<TestSuite::Math::ComplexCalculator> complexCalc = std::make_unique<TestSuite::Math::ComplexCalculator>();
    Integer squared = complexCalc->square(Integer(7));
    System::Print(String::Convert(squared));
    Integer pi = complexCalc->getPi();
    System::Print(String::Convert(pi));
    complexCalc->demonstrateOperators(Integer(20), Integer(4));
    std::unique_ptr<TestSuite::Collection::Counter> counter = std::make_unique<TestSuite::Collection::Counter>();
    counter->increment();
    counter->increment();
    counter->increment();
    Integer counterValue = counter->getValue();
    System::Print(String::Convert(counterValue));
    counter->decrement();
    Integer counterValue2 = counter->getValue();
    System::Print(String::Convert(counterValue2));
    counter->reset();
    std::unique_ptr<TestSuite::Collection::BoundedCounter> boundedCounter = std::make_unique<TestSuite::Collection::BoundedCounter>();
    boundedCounter->incrementSafe();
    std::unique_ptr<TestSuite::Final::SealedClass> sealed = std::make_unique<TestSuite::Final::SealedClass>();
    std::unique_ptr<TestSuite::Ownership::OwnershipDemo> ownershipDemo = std::make_unique<TestSuite::Ownership::OwnershipDemo>();
    ownershipDemo->demonstrateOwnership();
    String str1 = String(String("First"));
    String str2 = String(String("Second"));
    String str3 = String(String("Third"));
    String concatenated = Append(Append(Append(Append(Copy(str1), String(String(" "))), str2), String(String(" "))), str3);
    System::Print(concatenated);
    Integer expr1 = Integer(5) + Integer(3) * Integer(2);
    Integer expr2 = Integer(10) - Integer(2) / Integer(2);
    Integer expr3 = Integer(15) % Integer(4);
    System::Print(String::Convert(expr1));
    System::Print(String::Convert(expr2));
    System::Print(String::Convert(expr3));
    System::Print(String(String("Nested loops:")));
    for (Integer outer = Integer(0); outer < Integer(3); outer++) {
        for (Integer inner = Integer(0); inner < Integer(3); inner++) {
            String msg = Append(Append(String::Convert(outer), String(String(","))), String::Convert(inner));
            System::Print(msg);
        }
    }
    Integer isEqual = Integer(5);
    Integer notEqual = Integer(3);
    Integer a = Integer(1);
    Integer b = Integer(2);
    Integer c = Integer(3);
    Integer d = Integer(4);
    Integer e = Integer(5);
    Integer total = a + b + c + d + e;
    System::Print(String::Convert(total));
    String qualifiedTest = std::make_unique<TestSuite::Text::StringManipulator>()->process(str1);
    System::Print(String(String("Test 1")));
    System::Print(String(String("Test 2")));
    System::Print(String(String("Test 3")));
    System::Print(String(String("All features demonstrated successfully!")));
    return Integer(0);
}

