// Generated by XXML Compiler (Multi-file)
// Combined output from 2 module(s)

#include "../runtime/xxml_runtime.h"
#include <iostream>
#include <string>
#include <memory>
#include <cstdint>

// ============================================
// Module: __main__
// ============================================
int main() {
    System::PrintLine(String(String("======================================")));
    System::PrintLine(String(String("XXML Pure Standard Library Test")));
    System::PrintLine(String(String("======================================")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 1: If/Else ===")));
    Integer x = Integer(Integer(10));
    if (x == Integer(Integer(10))) {
        System::PrintLine(String(String("✓ If statement works!")));
    } else {
        System::PrintLine(String(String("✗ If statement failed")));
    }
    Integer y = Integer(Integer(5));
    if (y < Integer(Integer(3))) {
        System::PrintLine(String(String("✗ Should not print")));
    } else {
        System::PrintLine(String(String("✓ Else branch works!")));
    }
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 2: NativeType Primitives ===")));
    int64_t value1 = Integer(42);
    int64_t value2 = value1 * Integer(2);
    int64_t value3 = value2 + value1;
    System::Print(String(String("42 * 2 = ")));
    System::PrintLine(String::Convert(Integer(value2)));
    System::Print(String(String("84 + 42 = ")));
    System::PrintLine(String::Convert(Integer(value3)));
    System::PrintLine(String(String("✓ NativeType works for primitives")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 3: Syscall Memory ===")));
    void* buffer = Syscall::malloc(Integer(100));
    System::PrintLine(String(String("✓ Allocated 100 bytes")));
    Syscall::memset(buffer, Integer(65), Integer(10));
    System::PrintLine(String(String("✓ Filled 10 bytes with 'A'")));
    void* offset5 = buffer + Integer(5);
    Syscall::write_int64(offset5, Integer(12345));
    System::PrintLine(String(String("✓ Wrote int64 to offset 5")));
    int64_t readValue = Syscall::read_int64(offset5);
    System::Print(String(String("✓ Read back value: ")));
    System::PrintLine(String::Convert(Integer(readValue)));
    Syscall::free(buffer);
    System::PrintLine(String(String("✓ Freed memory")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 4: String Helpers ===")));
    String testStr = String(String("Hello, Pure XXML!"));
    void* cstr = testStr.toCString();
    System::Print(String(String("Original: ")));
    System::PrintLine(testStr);
    String convertedStr = String::FromCString(cstr);
    System::Print(String(String("Converted: ")));
    System::PrintLine(convertedStr);
    System::PrintLine(String(String("✓ toCString() and FromCString() work!")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 5: Syscall File I/O ===")));
    void* filePath = String(String("xxml_test.txt")).toCString();
    void* writeMode = String(String("w")).toCString();
    void* file = Syscall::fopen(filePath, writeMode);
    if (file != Integer(0)) {
        System::PrintLine(String(String("✓ Opened file for writing")));
        String content = String(String("Hello from Pure XXML!\nLine 2\nLine 3\n"));
        void* contentCStr = content.toCString();
        int64_t len = content.length();
        int64_t written = Syscall::fwrite(contentCStr, Integer(1), len, file);
        System::Print(String(String("✓ Wrote ")));
        System::Print(String::Convert(Integer(written)));
        System::PrintLine(String(String(" bytes")));
        Syscall::fclose(file);
        System::PrintLine(String(String("✓ Closed file")));
    }
    void* readMode = String(String("r")).toCString();
    void* file2 = Syscall::fopen(filePath, readMode);
    if (file2 != Integer(0)) {
        System::PrintLine(String(String("✓ Opened file for reading")));
        Syscall::fseek(file2, Integer(0), Integer(2));
        int64_t fileSize = Syscall::ftell(file2);
        Syscall::fseek(file2, Integer(0), Integer(0));
        System::Print(String(String("✓ File size: ")));
        System::Print(String::Convert(Integer(fileSize)));
        System::PrintLine(String(String(" bytes")));
        void* readBuffer = Syscall::malloc(fileSize + Integer(1));
        int64_t bytesRead = Syscall::fread(readBuffer, Integer(1), fileSize, file2);
        void* endPos = readBuffer + bytesRead;
        Syscall::write_int64(endPos, Integer(0));
        String fileContent = String::FromCString(readBuffer);
        System::PrintLine(String(String("✓ File contents:")));
        System::PrintLine(fileContent);
        Syscall::free(readBuffer);
        Syscall::fclose(file2);
    }
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("======================================")));
    System::PrintLine(String(String("All Tests PASSED!")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("Pure XXML Standard Library Features:")));
    System::PrintLine(String(String("  ✓ If/Else statements")));
    System::PrintLine(String(String("  ✓ NativeType<T> for primitives")));
    System::PrintLine(String(String("  ✓ Syscall::malloc/free/memset")));
    System::PrintLine(String(String("  ✓ Syscall::fopen/fread/fwrite/fclose")));
    System::PrintLine(String(String("  ✓ String::toCString()")));
    System::PrintLine(String(String("  ✓ String::FromCString()")));
    System::PrintLine(String(String("  ✓ Pointer arithmetic")));
    System::PrintLine(String(String("  ✓ Comparison operators")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("Foundation complete for pure XXML")));
    System::PrintLine(String(String("data structures and algorithms!")));
    System::PrintLine(String(String("======================================")));
}



// Module: __main__
int main() {
    System::PrintLine(String(String("======================================")));
    System::PrintLine(String(String("XXML Pure Standard Library Test")));
    System::PrintLine(String(String("======================================")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 1: If/Else ===")));
    Integer x = Integer(Integer(10));
    if (x == Integer(Integer(10))) {
        System::PrintLine(String(String("✓ If statement works!")));
    } else {
        System::PrintLine(String(String("✗ If statement failed")));
    }
    Integer y = Integer(Integer(5));
    if (y < Integer(Integer(3))) {
        System::PrintLine(String(String("✗ Should not print")));
    } else {
        System::PrintLine(String(String("✓ Else branch works!")));
    }
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 2: NativeType Primitives ===")));
    int64_t value1 = Integer(42);
    int64_t value2 = value1 * Integer(2);
    int64_t value3 = value2 + value1;
    System::Print(String(String("42 * 2 = ")));
    System::PrintLine(String::Convert(Integer(value2)));
    System::Print(String(String("84 + 42 = ")));
    System::PrintLine(String::Convert(Integer(value3)));
    System::PrintLine(String(String("✓ NativeType works for primitives")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 3: Syscall Memory ===")));
    void* buffer = Syscall::malloc(Integer(100));
    System::PrintLine(String(String("✓ Allocated 100 bytes")));
    Syscall::memset(buffer, Integer(65), Integer(10));
    System::PrintLine(String(String("✓ Filled 10 bytes with 'A'")));
    void* offset5 = buffer + Integer(5);
    Syscall::write_int64(offset5, Integer(12345));
    System::PrintLine(String(String("✓ Wrote int64 to offset 5")));
    int64_t readValue = Syscall::read_int64(offset5);
    System::Print(String(String("✓ Read back value: ")));
    System::PrintLine(String::Convert(Integer(readValue)));
    Syscall::free(buffer);
    System::PrintLine(String(String("✓ Freed memory")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 4: String Helpers ===")));
    String testStr = String(String("Hello, Pure XXML!"));
    void* cstr = testStr.toCString();
    System::Print(String(String("Original: ")));
    System::PrintLine(testStr);
    String convertedStr = String::FromCString(cstr);
    System::Print(String(String("Converted: ")));
    System::PrintLine(convertedStr);
    System::PrintLine(String(String("✓ toCString() and FromCString() work!")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("=== Test 5: Syscall File I/O ===")));
    void* filePath = String(String("xxml_test.txt")).toCString();
    void* writeMode = String(String("w")).toCString();
    void* file = Syscall::fopen(filePath, writeMode);
    if (file != Integer(0)) {
        System::PrintLine(String(String("✓ Opened file for writing")));
        String content = String(String("Hello from Pure XXML!\nLine 2\nLine 3\n"));
        void* contentCStr = content.toCString();
        int64_t len = content.length();
        int64_t written = Syscall::fwrite(contentCStr, Integer(1), len, file);
        System::Print(String(String("✓ Wrote ")));
        System::Print(String::Convert(Integer(written)));
        System::PrintLine(String(String(" bytes")));
        Syscall::fclose(file);
        System::PrintLine(String(String("✓ Closed file")));
    }
    void* readMode = String(String("r")).toCString();
    void* file2 = Syscall::fopen(filePath, readMode);
    if (file2 != Integer(0)) {
        System::PrintLine(String(String("✓ Opened file for reading")));
        Syscall::fseek(file2, Integer(0), Integer(2));
        int64_t fileSize = Syscall::ftell(file2);
        Syscall::fseek(file2, Integer(0), Integer(0));
        System::Print(String(String("✓ File size: ")));
        System::Print(String::Convert(Integer(fileSize)));
        System::PrintLine(String(String(" bytes")));
        void* readBuffer = Syscall::malloc(fileSize + Integer(1));
        int64_t bytesRead = Syscall::fread(readBuffer, Integer(1), fileSize, file2);
        void* endPos = readBuffer + bytesRead;
        Syscall::write_int64(endPos, Integer(0));
        String fileContent = String::FromCString(readBuffer);
        System::PrintLine(String(String("✓ File contents:")));
        System::PrintLine(fileContent);
        Syscall::free(readBuffer);
        Syscall::fclose(file2);
    }
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("======================================")));
    System::PrintLine(String(String("All Tests PASSED!")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("Pure XXML Standard Library Features:")));
    System::PrintLine(String(String("  ✓ If/Else statements")));
    System::PrintLine(String(String("  ✓ NativeType<T> for primitives")));
    System::PrintLine(String(String("  ✓ Syscall::malloc/free/memset")));
    System::PrintLine(String(String("  ✓ Syscall::fopen/fread/fwrite/fclose")));
    System::PrintLine(String(String("  ✓ String::toCString()")));
    System::PrintLine(String(String("  ✓ String::FromCString()")));
    System::PrintLine(String(String("  ✓ Pointer arithmetic")));
    System::PrintLine(String(String("  ✓ Comparison operators")));
    System::PrintLine(String(String("")));
    System::PrintLine(String(String("Foundation complete for pure XXML")));
    System::PrintLine(String(String("data structures and algorithms!")));
    System::PrintLine(String(String("======================================")));
}


