; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [13 x i8] c"Test value: \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"Sum: \00"
@.str.2 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"
@.str.3 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"

; ============================================
; Class: List_Integer
; ============================================
%class.List_Integer = type { i64, i64, i64 }

; Constructor for List_Integer
define ptr @List_Integer_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: add
define ptr @List_Integer_add(ptr %this, ptr %value) #1 {
    ; Instantiate owned variable: offset
    %r0 = alloca i64
    %r1 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r2 = load i64, ptr %r1
    %r3 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r4 = load i64, ptr %r3
    %r5 = mul i64 %r4, 8
    %r6 = add i64 %r2, %r5
    store i64 %r6, ptr %r0
    %r7 = load i64, ptr %r0
    %r9 = inttoptr i64 %r7 to ptr
    %r8 = call ptr @Syscall_ptr_write(ptr %r9, ptr %value)
    ; Instantiate owned variable: newCount
    %r10 = alloca i64
    %r11 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r12 = load i64, ptr %r11
    %r13 = add i64 %r12, 1
    store i64 %r13, ptr %r10
    %r15 = inttoptr i64 8 to ptr
    %r14 = call ptr @Syscall_memcpy(ptr %r15)
    ret ptr null  ; implicit return
}

; Method: get
define ptr @List_Integer_get(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r16 = alloca i64
    store i64 0, ptr %r16
    ; Instantiate owned variable: idx
    %r17 = alloca i64
    %r18 = call i64 @indextoInt64()
    store i64 %r18, ptr %r17
    ; Instantiate owned variable: offset
    %r19 = alloca i64
    %r20 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r21 = load i64, ptr %r20
    %r22 = load i64, ptr %r17
    %r23 = mul i64 %r22, 8
    %r24 = add i64 %r21, %r23
    store i64 %r24, ptr %r19
    %r25 = load i64, ptr %r19
    %r27 = inttoptr i64 %r25 to ptr
    %r26 = call ptr @Syscall_ptr_read(ptr %r27)
    ret ptr %r26
}

; Method: set
define ptr @List_Integer_set(ptr %this, ptr %index, ptr %value) #1 {
    ; Instantiate owned variable: zero
    %r28 = alloca i64
    store i64 0, ptr %r28
    ; Instantiate owned variable: idx
    %r29 = alloca i64
    %r30 = call i64 @indextoInt64()
    store i64 %r30, ptr %r29
    ; Instantiate owned variable: offset
    %r31 = alloca i64
    %r32 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r33 = load i64, ptr %r32
    %r34 = load i64, ptr %r29
    %r35 = mul i64 %r34, 8
    %r36 = add i64 %r33, %r35
    store i64 %r36, ptr %r31
    %r37 = load i64, ptr %r31
    %r39 = inttoptr i64 %r37 to ptr
    %r38 = call ptr @Syscall_ptr_write(ptr %r39, ptr %value)
    ret ptr null  ; implicit return
}

; Method: size
define ptr @List_Integer_size(ptr %this) #1 {
    %r40 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r41 = load i64, ptr %r40
    %r42 = call ptr @Integer_Constructor(i64 %r41)
    ret ptr %r42
}

; Method: isEmpty
define ptr @List_Integer_isEmpty(ptr %this) #1 {
    %r43 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r44 = load i64, ptr %r43
    %r45 = icmp eq i64 %r44, 0
    %r46 = call ptr @Bool_Constructor(i64 %r45)
    ret ptr %r46
}

; Method: clear
define ptr @List_Integer_clear(ptr %this) #1 {
    ; Instantiate owned variable: zero
    %r47 = alloca i64
    store i64 0, ptr %r47
    %r49 = inttoptr i64 8 to ptr
    %r48 = call ptr @Syscall_memcpy(ptr %r49)
    ret ptr null  ; implicit return
}

; Method: remove
define ptr @List_Integer_remove(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r50 = alloca i64
    store i64 0, ptr %r50
    ; Instantiate owned variable: idx
    %r51 = alloca i64
    %r52 = call i64 @indextoInt64()
    store i64 %r52, ptr %r51
    ; Instantiate owned variable: i
    %r53 = alloca i64
    %r54 = load i64, ptr %r51
    store i64 %r54, ptr %r53
    ; Instantiate owned variable: one
    %r55 = alloca i64
    store i64 1, ptr %r55
    ; Instantiate owned variable: newCount
    %r56 = alloca i64
    %r57 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r58 = load i64, ptr %r57
    %r59 = load i64, ptr %r55
    %r60 = sub i64 %r58, %r59
    store i64 %r60, ptr %r56
    %r62 = inttoptr i64 8 to ptr
    %r61 = call ptr @Syscall_memcpy(ptr %r62)
    ret ptr null  ; implicit return
}

; Method: dispose
define ptr @List_Integer_dispose(ptr %this) #1 {
    ; Instantiate owned variable: zero64
    %r63 = alloca i64
    store i64 0, ptr %r63
    %r65 = inttoptr i64 8 to ptr
    %r64 = call ptr @Syscall_memcpy(ptr %r65)
    %r67 = inttoptr i64 8 to ptr
    %r66 = call ptr @Syscall_memcpy(ptr %r67)
    ret ptr null  ; implicit return
}


; ============================================
; Class: MyNamespace::SomeClass_MyNamespace__MyClass
; ============================================
%class.MyNamespace_SomeClass_MyNamespace__MyClass = type { i8 }

; Method: run
define ptr @MyNamespace_SomeClass_MyNamespace__MyClass_run(ptr %this) #1 {
    ; Instantiate owned variable: myT
    %r68 = alloca ptr
    ; template parameter instantiation (not supported): T::::Constructor
    store ptr null, ptr %r68
    %r69 = load ptr, ptr %r68
    %r70 = call ptr @MyClass_getValue(ptr %r69)
    %r72 = inttoptr i64 53 to ptr
    %r71 = call ptr @MyClass_add(ptr %r70, ptr %r72)
    %r73 = call ptr @MyClass_toString(ptr %r71)
    %r74 = call ptr @Console_printLine(ptr %r73)
    ret ptr null  ; implicit return
}


; import Language::Core
; import Language::Collections
; import Language::System
; namespace MyNamespace
; constraint MyConstraint
; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: getValue
define ptr @MyClass_getValue(ptr %this) #1 {
    %r75 = call ptr @Integer_Constructor(i64 42)
    ret ptr %r75
}


define i32 @main() #1 {
    ; Instantiate owned variable: myClass
    %r76 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r76
    ; Instantiate owned variable: testValue
    %r77 = alloca ptr
    %r78 = call ptr @Integer_Constructor(i64 42)
    store ptr %r78, ptr %r77
    ; Instantiate owned variable: testStr
    %r79 = alloca ptr
    %r80 = load ptr, ptr %r77
    %r81 = call ptr @Integer_toString(ptr %r80)
    store ptr %r81, ptr %r79
    ; Instantiate owned variable: deez
    %r82 = alloca ptr
    %r83 = call ptr @List_Integer_Constructor()
    store ptr %r83, ptr %r82
    ; Instantiate owned variable: nutz
    %r84 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r84
    %r85 = load ptr, ptr %r82
    %r86 = call ptr @Integer_Constructor(i64 5)
    %r87 = call ptr @List_Integer_add(%class.List_Integer %r85, ptr %r86)
    %r88 = load ptr, ptr %r84
    %r89 = call ptr @MyNamespace_SomeClass_MyNamespace_MyClass_run(%class.MyNamespace_SomeClass_MyNamespace_MyClass %r88)
    %r90 = call ptr @String_Constructor(ptr @.str.0)
    %r91 = load ptr, ptr %r79
    %r92 = call ptr @String_append(ptr %r90, ptr %r91)
    %r93 = call ptr @Console_printLine(ptr %r92)
    ; Instantiate owned variable: num1
    %r94 = alloca ptr
    %r95 = call ptr @Integer_Constructor(i64 10)
    store ptr %r95, ptr %r94
    ; Instantiate owned variable: num2
    %r96 = alloca ptr
    %r97 = call ptr @Integer_Constructor(i64 32)
    store ptr %r97, ptr %r96
    ; Instantiate owned variable: sum
    %r98 = alloca ptr
    %r99 = load ptr, ptr %r94
    %r100 = load ptr, ptr %r96
    %r101 = call ptr @Integer_add(ptr %r99, ptr %r100)
    store ptr %r101, ptr %r98
    ; Instantiate owned variable: sumStr
    %r102 = alloca ptr
    %r103 = load ptr, ptr %r98
    %r104 = call ptr @Integer_toString(ptr %r103)
    store ptr %r104, ptr %r102
    %r105 = call ptr @String_Constructor(ptr @.str.1)
    %r106 = load ptr, ptr %r102
    %r107 = call ptr @String_append(ptr %r105, ptr %r106)
    %r108 = call ptr @Console_printLine(ptr %r107)
    %r109 = call ptr @String_Constructor(ptr @.str.2)
    %r110 = load ptr, ptr %r82
    %r111 = call ptr @Integer_Constructor(i64 0)
    %r112 = call ptr @List_Integer_get(%class.List_Integer %r110, ptr %r111)
    %r113 = call ptr @List_toString(ptr %r112)
    %r114 = call ptr @String_append(ptr %r109, ptr %r113)
    %r115 = call ptr @Console_printLine(ptr %r114)
    %r116 = call ptr @String_Constructor(ptr @.str.3)
    %r117 = call ptr @Console_printLine(ptr %r116)
    ret i32 0
}
