; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [13 x i8] c"Test value: \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"Sum: \00"
@.str.2 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"
@.str.3 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"

; import Language::Core
; import Language::Collections
; import Language::System
; namespace MyNamespace
; constraint MyConstraint
; ============================================
; Class: SomeClass
; Template parameters: 1
; ============================================
%class.SomeClass = type { i8 }

; Method: run
define ptr @SomeClass_run(ptr %this) #1 {
    ; Instantiate owned variable: myT
    %r0 = alloca ptr
    ; template parameter instantiation (not supported): T::::Constructor
    store ptr null, ptr %r0
    %r1 = load ptr, ptr %r0
    %r2 = call ptr @T_getValue(ptr %r1)
    %r3 = load ptr, ptr %r2
    %r4 = call ptr @T_add(ptr %r3, i64 53)
    %r5 = load ptr, ptr %r4
    %r6 = call ptr @T_toString(ptr %r5)
    %r7 = call ptr @Console_printLine(ptr %r6)
    ret ptr null  ; implicit return
}


; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: getValue
define ptr @MyClass_getValue(ptr %this) #1 {
    %r8 = call ptr @Integer_Constructor(i64 42)
    ret ptr %r8
}


define i32 @main() #1 {
    ; Instantiate owned variable: myClass
    %r9 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r9
    ; Instantiate owned variable: testValue
    %r10 = alloca ptr
    %r11 = call ptr @Integer_Constructor(i64 42)
    store ptr %r11, ptr %r10
    ; Instantiate owned variable: testStr
    %r12 = alloca ptr
    %r13 = load ptr, ptr %r10
    %r14 = call ptr @Integer_toString(ptr %r13)
    store ptr %r14, ptr %r12
    ; Instantiate owned variable: deez
    %r15 = alloca ptr
    %r16 = call ptr @List_Constructor()
    store ptr %r16, ptr %r15
    ; Instantiate owned variable: nutz
    %r17 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r17
    %r18 = load ptr, ptr %r15
    %r19 = call ptr @Integer_Constructor(i64 5)
    %r20 = call ptr @List_add(ptr %r18, ptr %r19)
    %r21 = load ptr, ptr %r17
    %r22 = call ptr @SomeClass_run(ptr %r21)
    %r23 = call ptr @String_Constructor(ptr @.str.0)
    %r24 = load ptr, ptr %r23
    %r25 = call ptr @String_append(ptr %r24, ptr %r12)
    %r26 = call ptr @Console_printLine(ptr %r25)
    ; Instantiate owned variable: num1
    %r27 = alloca ptr
    %r28 = call ptr @Integer_Constructor(i64 10)
    store ptr %r28, ptr %r27
    ; Instantiate owned variable: num2
    %r29 = alloca ptr
    %r30 = call ptr @Integer_Constructor(i64 32)
    store ptr %r30, ptr %r29
    ; Instantiate owned variable: sum
    %r31 = alloca ptr
    %r32 = load ptr, ptr %r27
    %r33 = call ptr @Integer_add(ptr %r32, ptr %r29)
    store ptr %r33, ptr %r31
    ; Instantiate owned variable: sumStr
    %r34 = alloca ptr
    %r35 = load ptr, ptr %r31
    %r36 = call ptr @Integer_toString(ptr %r35)
    store ptr %r36, ptr %r34
    %r37 = call ptr @String_Constructor(ptr @.str.1)
    %r38 = load ptr, ptr %r37
    %r39 = call ptr @String_append(ptr %r38, ptr %r34)
    %r40 = call ptr @Console_printLine(ptr %r39)
    %r41 = call ptr @String_Constructor(ptr @.str.2)
    %r42 = load ptr, ptr %r41
    %r43 = load ptr, ptr %r15
    %r44 = call ptr @Integer_Constructor(i64 0)
    %r45 = call ptr @List_get(ptr %r43, ptr %r44)
    %r46 = load ptr, ptr %r45
    %r47 = call ptr @List_toString(ptr %r46)
    %r48 = call ptr @String_append(ptr %r42, ptr %r47)
    %r49 = call ptr @Console_printLine(ptr %r48)
    %r50 = call ptr @String_Constructor(ptr @.str.3)
    %r51 = call ptr @Console_printLine(ptr %r50)
    ret i32 0
}
