; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [13 x i8] c"Test value: \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"Sum: \00"
@.str.2 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"
@.str.3 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"

; ============================================
; Class: List_Integer
; ============================================
%class.List_Integer = type { %class.NativeType_ptr, %class.NativeType_int64, %class.NativeType_int64 }

; Constructor for List_Integer
define ptr @List_Integer_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: add
define ptr @List_Integer_add(ptr %this, ptr %value) #1 {
    ; Instantiate owned variable: offset
    %r0 = alloca ptr
    %r1 = ; LLVM: @count * 8
    %r2 = ; LLVM: @dataPtr + %r1
    store ptr %r2, ptr %r0
    %r3 = load ptr, ptr %r0
    %r4 = call ptr @Syscall_ptr_write(ptr %r3, ptr %value)
    ; Instantiate owned variable: newCount
    %r5 = alloca ptr
    %r6 = ; LLVM: @count + 1
    store ptr %r6, ptr %r5
    %r7 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: get
define ptr @List_Integer_get(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r8 = alloca ptr
    store ptr null, ptr %r8
    ; Instantiate owned variable: idx
    %r9 = alloca ptr
    %r10 = call ptr @indextoInt64()
    store ptr %r10, ptr %r9
    ; Instantiate owned variable: offset
    %r11 = alloca ptr
    %r12 = ; LLVM: %r9 * 8
    %r13 = ; LLVM: @dataPtr + %r12
    store ptr %r13, ptr %r11
    %r14 = load ptr, ptr %r11
    %r15 = call ptr @Syscall_ptr_read(ptr %r14)
    ret ptr %r15
}

; Method: set
define ptr @List_Integer_set(ptr %this, ptr %index, ptr %value) #1 {
    ; Instantiate owned variable: zero
    %r16 = alloca ptr
    store ptr null, ptr %r16
    ; Instantiate owned variable: idx
    %r17 = alloca ptr
    %r18 = call ptr @indextoInt64()
    store ptr %r18, ptr %r17
    ; Instantiate owned variable: offset
    %r19 = alloca ptr
    %r20 = ; LLVM: %r17 * 8
    %r21 = ; LLVM: @dataPtr + %r20
    store ptr %r21, ptr %r19
    %r22 = load ptr, ptr %r19
    %r23 = call ptr @Syscall_ptr_write(ptr %r22, ptr %value)
    ret ptr null  ; implicit return
}

; Method: size
define ptr @List_Integer_size(ptr %this) #1 {
    %r24 = call ptr @Integer_Constructor(ptr @count)
    ret ptr %r24
}

; Method: isEmpty
define ptr @List_Integer_isEmpty(ptr %this) #1 {
    %r25 = ; LLVM: @count == 0
    %r26 = call ptr @Bool_Constructor(ptr %r25)
    ret ptr %r26
}

; Method: clear
define ptr @List_Integer_clear(ptr %this) #1 {
    ; Instantiate owned variable: zero
    %r27 = alloca ptr
    store ptr null, ptr %r27
    %r28 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: remove
define ptr @List_Integer_remove(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r29 = alloca ptr
    store ptr null, ptr %r29
    ; Instantiate owned variable: idx
    %r30 = alloca ptr
    %r31 = call ptr @indextoInt64()
    store ptr %r31, ptr %r30
    ; Instantiate owned variable: i
    %r32 = alloca ptr
    store ptr %r30, ptr %r32
    ; Instantiate owned variable: one
    %r33 = alloca ptr
    store ptr 1, ptr %r33
    ; Instantiate owned variable: newCount
    %r34 = alloca ptr
    %r35 = ; LLVM: @count - %r33
    store ptr %r35, ptr %r34
    %r36 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: dispose
define ptr @List_Integer_dispose(ptr %this) #1 {
    ; Instantiate owned variable: zero64
    %r37 = alloca ptr
    store ptr null, ptr %r37
    %r38 = call ptr @Syscall_memcpy(i64 8)
    %r39 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}


; ============================================
; Class: MyNamespace::SomeClass_MyNamespace__MyClass
; ============================================
%class.MyNamespace::SomeClass_MyNamespace__MyClass = type { i8 }

; Method: run
define ptr @MyNamespace_SomeClass_MyNamespace__MyClass_run(ptr %this) #1 {
    ; Instantiate owned variable: myT
    %r40 = alloca ptr
    ; template parameter instantiation (not supported): T::::Constructor
    store ptr null, ptr %r40
    %r41 = load ptr, ptr %r40
    %r42 = call ptr @MyClass_getValue(ptr %r41)
    %r43 = call ptr @MyClass_add(ptr %r42, i64 53)
    %r44 = call ptr @MyClass_toString(ptr %r43)
    %r45 = call ptr @Console_printLine(ptr %r44)
    ret ptr null  ; implicit return
}


; import Language::Core
; import Language::Collections
; import Language::System
; namespace MyNamespace
; constraint MyConstraint
; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: getValue
define ptr @MyClass_getValue(ptr %this) #1 {
    %r46 = call ptr @Integer_Constructor(i64 42)
    ret ptr %r46
}


define i32 @main() #1 {
    ; Instantiate owned variable: myClass
    %r47 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r47
    ; Instantiate owned variable: testValue
    %r48 = alloca ptr
    %r49 = call ptr @Integer_Constructor(i64 42)
    store ptr %r49, ptr %r48
    ; Instantiate owned variable: testStr
    %r50 = alloca ptr
    %r51 = load ptr, ptr %r48
    %r52 = call ptr @Integer_toString(ptr %r51)
    store ptr %r52, ptr %r50
    ; Instantiate owned variable: deez
    %r53 = alloca ptr
    %r54 = call ptr @List_Integer_Constructor()
    store ptr %r54, ptr %r53
    ; Instantiate owned variable: nutz
    %r55 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r55
    %r56 = load ptr, ptr %r53
    %r57 = call ptr @Integer_Constructor(i64 5)
    %r58 = call ptr @List_Integer_add(ptr %r56, ptr %r57)
    %r59 = load ptr, ptr %r55
    %r60 = call ptr @MyNamespace_SomeClass_MyNamespace_MyClass_run(ptr %r59)
    %r61 = call ptr @String_Constructor(ptr @.str.0)
    %r62 = load ptr, ptr %r50
    %r63 = call ptr @String_append(ptr %r61, ptr %r62)
    %r64 = call ptr @Console_printLine(ptr %r63)
    ; Instantiate owned variable: num1
    %r65 = alloca ptr
    %r66 = call ptr @Integer_Constructor(i64 10)
    store ptr %r66, ptr %r65
    ; Instantiate owned variable: num2
    %r67 = alloca ptr
    %r68 = call ptr @Integer_Constructor(i64 32)
    store ptr %r68, ptr %r67
    ; Instantiate owned variable: sum
    %r69 = alloca ptr
    %r70 = load ptr, ptr %r65
    %r71 = load ptr, ptr %r67
    %r72 = call ptr @Integer_add(ptr %r70, ptr %r71)
    store ptr %r72, ptr %r69
    ; Instantiate owned variable: sumStr
    %r73 = alloca ptr
    %r74 = load ptr, ptr %r69
    %r75 = call ptr @Integer_toString(ptr %r74)
    store ptr %r75, ptr %r73
    %r76 = call ptr @String_Constructor(ptr @.str.1)
    %r77 = load ptr, ptr %r73
    %r78 = call ptr @String_append(ptr %r76, ptr %r77)
    %r79 = call ptr @Console_printLine(ptr %r78)
    %r80 = call ptr @String_Constructor(ptr @.str.2)
    %r81 = load ptr, ptr %r53
    %r82 = call ptr @Integer_Constructor(i64 0)
    %r83 = call ptr @List_Integer_get(ptr %r81, ptr %r82)
    %r84 = call ptr @List_toString(ptr %r83)
    %r85 = call ptr @String_append(ptr %r80, ptr %r84)
    %r86 = call ptr @Console_printLine(ptr %r85)
    %r87 = call ptr @String_Constructor(ptr @.str.3)
    %r88 = call ptr @Console_printLine(ptr %r87)
    ret i32 0
}
