; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; NativeType Operations
declare ptr @NativeType_int64_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; None Operations
declare ptr @None_Constructor()

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare i64 @Console_readInt()
declare ptr @Console_readLine()
declare void @Console_print(ptr)
declare void @Console_printBool(i1)
declare void @Console_printInt(i64)
declare void @Console_printLine(ptr)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; Class: List_Integer
; ============================================
%class.List_Integer = type { ptr, i64, i64 }

; Constructor for List_Integer
define ptr @List_Integer_Constructor(ptr %this) #1 {
  ; Instantiate owned variable: nullPtr
  %1 = alloca ptr
  store ptr null, ptr %1
  ; Instantiate owned variable: zero
  %2 = alloca i64
  store i64 0, ptr %2
  %3 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
  %4 = load ptr, ptr %1
  %r0 = call ptr @xxml_memcpy(ptr %3, ptr %4, i64 8)
  %5 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 1
  %6 = load ptr, ptr %2
  %r1 = call ptr @xxml_memcpy(ptr %5, ptr %6, i64 8)
  %7 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
  %8 = load ptr, ptr %2
  %r2 = call ptr @xxml_memcpy(ptr %7, ptr %8, i64 8)
  ret ptr %this
}

; Method: add
define void @List_Integer_add(ptr %this, i64 %value) #1 {
  %2 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
  %3 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 1
  %4 = ptrtoint ptr %2 to i64
  %5 = ptrtoint ptr %3 to i64
  %6 = icmp eq i64 %4, %5
  br i1 %6, label %if_then0, label %if_else1
if_then0:
      ; Instantiate owned variable: newCapacity
      %7 = alloca i64
      %8 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 1
      %9 = ptrtoint ptr %8 to i64
      %10 = mul i64 %9, 2
      store i64 %10, ptr %7
      %11 = load i64, ptr %7
      %12 = icmp eq i64 %11, 0
      br i1 %12, label %if_then3, label %if_else4
if_then3:
          store i64 8, ptr %7
        br label %if_end5
if_else4:
          br label %if_end5
if_end5:
            ; Instantiate owned variable: newData
            %13 = alloca ptr
            %14 = load i64, ptr %7
            %15 = mul i64 %14, 8
            %r3 = call ptr @xxml_malloc(i64 %15)
            store i64 %15, ptr %13
            %16 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
            %17 = ptrtoint ptr %16 to i64
            %18 = icmp ne i64 %17, 0
            br i1 %18, label %if_then6, label %if_else7
if_then6:
                %19 = load ptr, ptr %13
                %20 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                %21 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                %22 = ptrtoint ptr %21 to i64
                %23 = mul i64 %22, 8
                %r4 = call ptr @xxml_memcpy(ptr %19, ptr %20, i64 %23)
                %24 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                call void @xxml_free(ptr %24)
              br label %if_end8
if_else7:
                br label %if_end8
if_end8:
                  %25 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                  %26 = load ptr, ptr %13
                  %r5 = call ptr @xxml_memcpy(ptr %25, ptr %26, i64 8)
                  %27 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 1
                  %28 = load ptr, ptr %7
                  %r6 = call ptr @xxml_memcpy(ptr %27, ptr %28, i64 8)
                br label %if_end2
if_else1:
                  br label %if_end2
if_end2:
                    ; Instantiate owned variable: offset
                    %29 = alloca ptr
                    %30 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                    %31 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                    %32 = ptrtoint ptr %31 to i64
                    %33 = mul i64 %32, 8
                    %34 = ptrtoint ptr %30 to i64
                    %35 = add i64 %34, %33
                    %36 = inttoptr i64 %35 to ptr
                    store ptr %36, ptr %29
                    %37 = load ptr, ptr %29
                    call void @xxml_ptr_write(ptr %37, ptr %37)
                    ; Instantiate owned variable: newCount
                    %38 = alloca i64
                    %39 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                    %40 = ptrtoint ptr %39 to i64
                    %41 = add i64 %40, 1
                    %42 = inttoptr i64 %41 to ptr
                    store ptr %42, ptr %38
                    %43 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                    %44 = load ptr, ptr %38
                    %r7 = call ptr @xxml_memcpy(ptr %43, ptr %44, i64 8)
                    ret void
                  }
                  
                  ; Method: get
                  define i64 @List_Integer_get(ptr %this, i64 %index) #1 {
                    ; Instantiate owned variable: zero
                    %2 = alloca i64
                    store i64 0, ptr %2
                    ; Instantiate owned variable: idx
                    %3 = alloca i64
                    %4 = inttoptr i64 %index to ptr
                    %r8 = call i64 @Integer_toInt64(ptr %4)
                    store i64 0, ptr %3
                    %5 = load i64, ptr %3
                    %6 = load i64, ptr %2
                    %7 = icmp slt i64 %5, %6
                    br i1 %7, label %if_then9, label %if_else10
if_then9:
                        ; Instantiate owned variable: nullPtr
                        %8 = alloca ptr
                        store ptr null, ptr %8
                        %9 = load ptr, ptr %8
                        %r9 = call ptr @xxml_ptr_read(ptr %9)
                        %10 = ptrtoint ptr %9 to i64
                        ret i64 %10
if_else10:
                        br label %if_end11
if_end11:
                          %11 = load i64, ptr %3
                          %12 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                          %13 = ptrtoint ptr %12 to i64
                          %14 = icmp sge i64 %11, %13
                          br i1 %14, label %if_then12, label %if_else13
if_then12:
                              ; Instantiate owned variable: nullPtr
                              %15 = alloca ptr
                              store ptr null, ptr %15
                              %16 = load ptr, ptr %15
                              %r10 = call ptr @xxml_ptr_read(ptr %16)
                              %17 = ptrtoint ptr %16 to i64
                              ret i64 %17
if_else13:
                              br label %if_end14
if_end14:
                                ; Instantiate owned variable: offset
                                %18 = alloca ptr
                                %19 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                %20 = load i64, ptr %3
                                %21 = mul i64 %20, 8
                                %22 = ptrtoint ptr %19 to i64
                                %23 = add i64 %22, %21
                                %24 = inttoptr i64 %23 to ptr
                                store ptr %24, ptr %18
                                %25 = load ptr, ptr %18
                                %r11 = call ptr @xxml_ptr_read(ptr %25)
                                %26 = ptrtoint ptr %25 to i64
                                ret i64 %26
                              }
                              
                              ; Method: set
                              define void @List_Integer_set(ptr %this, i64 %index, i64 %value) #1 {
                                ; Instantiate owned variable: zero
                                %3 = alloca i64
                                store i64 0, ptr %3
                                ; Instantiate owned variable: idx
                                %4 = alloca i64
                                %5 = inttoptr i64 %index to ptr
                                %r12 = call i64 @Integer_toInt64(ptr %5)
                                store i64 0, ptr %4
                                %6 = load i64, ptr %4
                                %7 = load i64, ptr %3
                                %8 = icmp slt i64 %6, %7
                                br i1 %8, label %if_then15, label %if_else16
if_then15:
                                    ; None::Constructor() - no-op
                                    ret void
if_else16:
                                    br label %if_end17
if_end17:
                                      %9 = load i64, ptr %4
                                      %10 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                      %11 = ptrtoint ptr %10 to i64
                                      %12 = icmp sge i64 %9, %11
                                      br i1 %12, label %if_then18, label %if_else19
if_then18:
                                          ; None::Constructor() - no-op
                                          ret void
if_else19:
                                          br label %if_end20
if_end20:
                                            ; Instantiate owned variable: offset
                                            %13 = alloca ptr
                                            %14 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                            %15 = load i64, ptr %4
                                            %16 = mul i64 %15, 8
                                            %17 = ptrtoint ptr %14 to i64
                                            %18 = add i64 %17, %16
                                            %19 = inttoptr i64 %18 to ptr
                                            store ptr %19, ptr %13
                                            %20 = load ptr, ptr %13
                                            call void @xxml_ptr_write(ptr %20, ptr %20)
                                            ret void
                                          }
                                          
                                          ; Method: size
                                          define i64 @List_Integer_size(ptr %this) #1 {
                                            %1 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                            %2 = ptrtoint ptr %1 to i64
                                            %r13 = call ptr @Integer_Constructor(i64 %2)
                                            %3 = ptrtoint ptr %1 to i64
                                            ret i64 %3
                                          }
                                          
                                          ; Method: isEmpty
                                          define i1 @List_Integer_isEmpty(ptr %this) #1 {
                                            %1 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                            %2 = ptrtoint ptr %1 to i64
                                            %3 = icmp eq i64 %2, 0
                                            %r14 = call ptr @Bool_Constructor(i1 %3)
                                            ret i1 %3
                                          }
                                          
                                          ; Method: clear
                                          define void @List_Integer_clear(ptr %this) #1 {
                                            ; Instantiate owned variable: zero
                                            %1 = alloca i64
                                            store i64 0, ptr %1
                                            %2 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                            %3 = load ptr, ptr %1
                                            %r15 = call ptr @xxml_memcpy(ptr %2, ptr %3, i64 8)
                                            ret void
                                          }
                                          
                                          ; Method: remove
                                          define void @List_Integer_remove(ptr %this, i64 %index) #1 {
                                            ; Instantiate owned variable: zero
                                            %2 = alloca i64
                                            store i64 0, ptr %2
                                            ; Instantiate owned variable: idx
                                            %3 = alloca i64
                                            %4 = inttoptr i64 %index to ptr
                                            %r16 = call i64 @Integer_toInt64(ptr %4)
                                            store i64 0, ptr %3
                                            %5 = load i64, ptr %3
                                            %6 = load i64, ptr %2
                                            %7 = icmp slt i64 %5, %6
                                            br i1 %7, label %if_then21, label %if_else22
if_then21:
                                                ; None::Constructor() - no-op
                                                ret void
if_else22:
                                                br label %if_end23
if_end23:
                                                  %8 = load i64, ptr %3
                                                  %9 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                                  %10 = ptrtoint ptr %9 to i64
                                                  %11 = icmp sge i64 %8, %10
                                                  br i1 %11, label %if_then24, label %if_else25
if_then24:
                                                      ; None::Constructor() - no-op
                                                      ret void
if_else25:
                                                      br label %if_end26
if_end26:
                                                        ; Instantiate owned variable: i
                                                        %12 = alloca i64
                                                        %13 = load i64, ptr %3
                                                        store i64 %13, ptr %12
                                                        br label %while_cond27
while_cond27:
                                                            %14 = load i64, ptr %12
                                                            %15 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                                            %16 = ptrtoint ptr %15 to i64
                                                            %17 = icmp slt i64 %14, %16
                                                            br i1 %17, label %while_body28, label %while_end29
while_body28:
                                                              ; Instantiate owned variable: destOffset
                                                              %18 = alloca ptr
                                                              %19 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                                              %20 = load i64, ptr %12
                                                              %21 = mul i64 %20, 8
                                                              %22 = ptrtoint ptr %19 to i64
                                                              %23 = add i64 %22, %21
                                                              %24 = inttoptr i64 %23 to ptr
                                                              store ptr %24, ptr %18
                                                              ; Instantiate owned variable: nextIdx
                                                              %25 = alloca i64
                                                              %26 = load i64, ptr %12
                                                              %27 = add i64 %26, 1
                                                              store i64 %27, ptr %25
                                                              ; Instantiate owned variable: srcOffset
                                                              %28 = alloca ptr
                                                              %29 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                                              %30 = load i64, ptr %25
                                                              %31 = mul i64 %30, 8
                                                              %32 = ptrtoint ptr %29 to i64
                                                              %33 = add i64 %32, %31
                                                              %34 = inttoptr i64 %33 to ptr
                                                              store ptr %34, ptr %28
                                                              ; Instantiate owned variable: val
                                                              %35 = alloca i64
                                                              %36 = load ptr, ptr %28
                                                              %r17 = call ptr @xxml_ptr_read(ptr %36)
                                                              store ptr %36, ptr %35
                                                              %37 = load ptr, ptr %18
                                                              %38 = load i64, ptr %35
                                                              %39 = inttoptr i64 %38 to ptr
                                                              call void @xxml_ptr_write(ptr %37, ptr %39)
                                                              ; Move nextIdx to i
                                                              %40 = load i64, ptr %25
                                                              store i64 %40, ptr %12
                                                              br label %while_cond27
while_end29:
                                                              ; Instantiate owned variable: one
                                                              %41 = alloca i64
                                                              store i64 1, ptr %41
                                                              ; Instantiate owned variable: newCount
                                                              %42 = alloca i64
                                                              %43 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                                              %44 = load i64, ptr %41
                                                              %45 = ptrtoint ptr %43 to i64
                                                              %46 = sub i64 %45, %44
                                                              %47 = inttoptr i64 %46 to ptr
                                                              store ptr %47, ptr %42
                                                              %48 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                                              %49 = load ptr, ptr %42
                                                              %r18 = call ptr @xxml_memcpy(ptr %48, ptr %49, i64 8)
                                                              ret void
                                                            }
                                                            
                                                            ; Method: dispose
                                                            define void @List_Integer_dispose(ptr %this) #1 {
                                                              %1 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                                              %2 = ptrtoint ptr %1 to i64
                                                              %3 = icmp ne i64 %2, 0
                                                              br i1 %3, label %if_then30, label %if_else31
if_then30:
                                                                  %4 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                                                  call void @xxml_free(ptr %4)
                                                                  ; Instantiate owned variable: zero
                                                                  %5 = alloca ptr
                                                                  store ptr null, ptr %5
                                                                  %6 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
                                                                  %7 = load ptr, ptr %5
                                                                  %r19 = call ptr @xxml_memcpy(ptr %6, ptr %7, i64 8)
                                                                br label %if_end32
if_else31:
                                                                  br label %if_end32
if_end32:
                                                                    ; Instantiate owned variable: zero64
                                                                    %8 = alloca i64
                                                                    store i64 0, ptr %8
                                                                    %9 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
                                                                    %10 = load ptr, ptr %8
                                                                    %r20 = call ptr @xxml_memcpy(ptr %9, ptr %10, i64 8)
                                                                    %11 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 1
                                                                    %12 = load ptr, ptr %8
                                                                    %r21 = call ptr @xxml_memcpy(ptr %11, ptr %12, i64 8)
                                                                    ret void
                                                                  }
                                                                  
                                                                  
                                                                  ; import Language::Core
                                                                  ; import Language::Collections
                                                                  define i32 @main() #1 {
                                                                    ; Instantiate owned variable: myList
                                                                    %1 = alloca ptr
                                                                    %2 = call ptr @xxml_malloc(i64 24)
                                                                    %3 = inttoptr i64 2 to ptr
                                                                    %r22 = call ptr @List_Integer_Constructor(ptr %3)
                                                                    store i64 8, ptr %1
                                                                    %4 = load ptr, ptr %1
                                                                    %r23 = call ptr @Integer_Constructor(i64 0)
                                                                    %5 = inttoptr i64 4 to ptr
                                                                    %6 = inttoptr i64 0 to ptr
                                                                    call void @List_Integer_add(ptr %5, ptr %6)
                                                                    %7 = load ptr, ptr %1
                                                                    %r24 = call ptr @Integer_Constructor(i64 12)
                                                                    %8 = inttoptr i64 7 to ptr
                                                                    %9 = inttoptr i64 12 to ptr
                                                                    call void @List_Integer_add(ptr %8, ptr %9)
                                                                    %10 = load ptr, ptr %1
                                                                    %r25 = call ptr @Integer_Constructor(i64 55)
                                                                    %11 = inttoptr i64 10 to ptr
                                                                    %12 = inttoptr i64 55 to ptr
                                                                    call void @List_Integer_add(ptr %11, ptr %12)
                                                                    %13 = load ptr, ptr %1
                                                                    %r26 = call ptr @Integer_Constructor(i64 24)
                                                                    %14 = inttoptr i64 13 to ptr
                                                                    %15 = inttoptr i64 24 to ptr
                                                                    call void @List_Integer_add(ptr %14, ptr %15)
                                                                    %16 = load ptr, ptr %1
                                                                    %r27 = call ptr @Integer_Constructor(i64 92)
                                                                    %17 = inttoptr i64 16 to ptr
                                                                    %18 = inttoptr i64 92 to ptr
                                                                    call void @List_Integer_add(ptr %17, ptr %18)
                                                                    %19 = load ptr, ptr %1
                                                                    %r28 = call ptr @Integer_Constructor(i64 37)
                                                                    %20 = inttoptr i64 19 to ptr
                                                                    %21 = inttoptr i64 37 to ptr
                                                                    call void @List_Integer_add(ptr %20, ptr %21)
                                                                    %22 = load ptr, ptr %1
                                                                    %r29 = call ptr @Integer_Constructor(i64 19)
                                                                    %23 = inttoptr i64 22 to ptr
                                                                    %24 = inttoptr i64 19 to ptr
                                                                    call void @List_Integer_add(ptr %23, ptr %24)
                                                                    %25 = alloca i64
                                                                    %r30 = call ptr @Integer_Constructor(i64 0)
                                                                    store i64 0, ptr %25
                                                                    %26 = load ptr, ptr %1
                                                                    %27 = inttoptr i64 26 to ptr
                                                                    %r31 = call ptr @List_Integer_size(ptr %27)
                                                                    %28 = alloca i64
                                                                    store i64 0, ptr %28
                                                                    br label %for_cond33
for_cond33:
                                                                        %29 = load i64, ptr %25
                                                                        %30 = load i64, ptr %28
                                                                        %31 = call i1 @Integer_lt(i64 %29, i64 %30)
                                                                        br i1 %31, label %for_body34, label %for_end36
for_body34:
                                                                          %32 = load ptr, ptr %12
                                                                          %33 = inttoptr i64 32 to ptr
                                                                          %r32 = call ptr @NativeType_int64_toString(ptr %33)
                                                                          %34 = inttoptr i64 0 to ptr
                                                                          call void @Console_printLine(ptr %34)
                                                                          br label %for_incr35
for_incr35:
                                                                            %35 = load i64, ptr %25
                                                                            %36 = call ptr @Integer_Constructor(i64 1)
                                                                            %37 = call ptr @Integer_add(i64 %35, ptr %36)
                                                                            store ptr %37, ptr %25
                                                                            br label %for_cond33
for_end36:
                                                                            ret i32 0
                                                                          }
