// Generated by XXML Compiler
// Do not edit this file manually

#include "runtime/xxml_runtime.h"
#include <iostream>
#include <string>
#include <memory>
#include <cstdint>

int main() {
    System::Print(String(String("=== XXML Standard Library Demo ===\n\n")));
    System::Print(String(String("--- String Operations ---\n")));
    String text = String(String("Hello, XXML!"));
    System::Print(String(String("Original: ")));
    System::Print(text);
    System::Print(String(String("\n")));
    String upper = text.toUpperCase();
    System::Print(String(String("Uppercase: ")));
    System::Print(upper);
    System::Print(String(String("\n")));
    String lower = text.toLowerCase();
    System::Print(String(String("Lowercase: ")));
    System::Print(lower);
    System::Print(String(String("\n")));
    String reversed = text.reverse();
    System::Print(String(String("Reversed: ")));
    System::Print(reversed);
    System::Print(String(String("\n")));
    Integer len = text.length();
    System::Print(String(String("Length: ")));
    System::Print(String::Convert(len));
    System::Print(String(String("\n")));
    String repeated = String(String("X")).repeat(Integer(Integer(5)));
    System::Print(String(String("Repeated: ")));
    System::Print(repeated);
    System::Print(String(String("\n\n")));
    System::Print(String(String("--- String Search ---\n")));
    String searchText = String(String("The quick brown fox jumps over the lazy dog"));
    System::Print(searchText);
    System::Print(String(String("\n")));
    Integer foxPos = searchText.indexOf(String(String("fox")));
    System::Print(String(String("Position of 'fox': ")));
    System::Print(String::Convert(foxPos));
    System::Print(String(String("\n")));
    Bool containsFox = searchText.contains(String(String("fox")));
    System::Print(String(String("Contains 'fox': ")));
    System::Print(String::Convert(containsFox));
    System::Print(String(String("\n")));
    Bool startsWithThe = searchText.startsWith(String(String("The")));
    System::Print(String(String("Starts with 'The': ")));
    System::Print(String::Convert(startsWithThe));
    System::Print(String(String("\n")));
    String replaced = searchText.replace(String(String("fox")), String(String("cat")));
    System::Print(String(String("After replace: ")));
    System::Print(replaced);
    System::Print(String(String("\n\n")));
    System::Print(String(String("--- Math Operations ---\n")));
    Integer a = Integer(Integer(42));
    Integer b = Integer(-Integer(17));
    Integer absVal = Math::abs(b);
    System::Print(String(String("abs(-17) = ")));
    System::Print(String::Convert(absVal));
    System::Print(String(String("\n")));
    Integer minVal = Math::min(a, b);
    System::Print(String(String("min(42, -17) = ")));
    System::Print(String::Convert(minVal));
    System::Print(String(String("\n")));
    Integer maxVal = Math::max(a, b);
    System::Print(String(String("max(42, -17) = ")));
    System::Print(String::Convert(maxVal));
    System::Print(String(String("\n")));
    Integer power = Math::pow(Integer(Integer(2)), Integer(Integer(10)));
    System::Print(String(String("2^10 = ")));
    System::Print(String::Convert(power));
    System::Print(String(String("\n")));
    Integer sqrtVal = Math::sqrt(Integer(Integer(144)));
    System::Print(String(String("sqrt(144) = ")));
    System::Print(String::Convert(sqrtVal));
    System::Print(String(String("\n\n")));
    System::Print(String(String("--- Number Theory ---\n")));
    Integer num1 = Integer(Integer(48));
    Integer num2 = Integer(Integer(18));
    Integer gcdVal = Math::gcd(num1, num2);
    System::Print(String(String("gcd(48, 18) = ")));
    System::Print(String::Convert(gcdVal));
    System::Print(String(String("\n")));
    Integer lcmVal = Math::lcm(num1, num2);
    System::Print(String(String("lcm(48, 18) = ")));
    System::Print(String::Convert(lcmVal));
    System::Print(String(String("\n")));
    Integer fact = Math::factorial(Integer(Integer(5)));
    System::Print(String(String("5! = ")));
    System::Print(String::Convert(fact));
    System::Print(String(String("\n")));
    System::Print(String(String("Fibonacci sequence (first 10): ")));
    for (Integer i = Integer(0); i < Integer(10); i++) {
        Integer fib = Math::fibonacci(i);
        System::Print(String::Convert(fib));
        System::Print(String(String(" ")));
    }
    System::Print(String(String("\n")));
    System::Print(String(String("Prime check (2-20): ")));
    for (Integer n = Integer(2); n < Integer(21); n++) {
        Bool prime = Math::isPrime(n);
        String primeStr = String::Convert(prime);
        System::Print(String::Convert(n));
        System::Print(String(String(":")));
        System::Print(primeStr);
        System::Print(String(String(" ")));
    }
    System::Print(String(String("\n\n")));
    System::Print(String(String("--- Type Conversions ---\n")));
    String numStr = String(String("12345"));
    Integer parsed = numStr.toInteger();
    System::Print(String(String("Parsed '12345' to: ")));
    System::Print(String::Convert(parsed));
    System::Print(String(String("\n")));
    Integer doubled = parsed * Integer(Integer(2));
    System::Print(String(String("Doubled: ")));
    System::Print(String::Convert(doubled));
    System::Print(String(String("\n\n")));
    System::Print(String(String("=== Demo Complete ===\n")));
    return Integer(0);
}

