// Generated by XXML Compiler (Multi-file)
// Combined output from 2 module(s)

#include "../runtime/xxml_runtime.h"
#include <iostream>
#include <string>
#include <memory>
#include <cstdint>

// ============================================
// Module: __main__
// ============================================
int main() {
    System::PrintLine(String(String("Template class defined")));
}



// Module: __main__
int main() {
    System::PrintLine(String(String("Template class defined")));
}


