// Generated by XXML Compiler (Multi-file)
// Combined output from 2 module(s)

#include "../runtime/xxml_runtime.h"
#include <iostream>
#include <string>
#include <memory>
#include <cstdint>

// ============================================
// Module: __main__
// ============================================
int main() {
    Integer x = Integer(Integer(10));
    if (x == Integer(Integer(10))) {
        System::PrintLine(String(String("x equals 10!")));
    } else {
        System::PrintLine(String(String("x does not equal 10")));
    }
    System::PrintLine(String(String("Test completed!")));
}



// Module: __main__
int main() {
    Integer x = Integer(Integer(10));
    if (x == Integer(Integer(10))) {
        System::PrintLine(String(String("x equals 10!")));
    } else {
        System::PrintLine(String(String("x does not equal 10")));
    }
    System::PrintLine(String(String("Test completed!")));
}


