; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [13 x i8] c"Test value: \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"Sum: \00"
@.str.2 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"
@.str.3 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"

; ============================================
; Class: List_Integer
; ============================================
%class.List_Integer = type { i64, i64, i64 }

; Constructor for List_Integer
define ptr @List_Integer_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: add
define ptr @List_Integer_add(ptr %this, ptr %value) #1 {
    ; Instantiate owned variable: offset
    %r0 = alloca i64
    %r1 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r2 = load i64, ptr %r1
    %r3 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r4 = load i64, ptr %r3
    %r5 = mul i64 %r4, 8
    %r6 = add i64 %r2, %r5
    store i64 %r6, ptr %r0
    %r7 = load i64, ptr %r0
    %r8 = call ptr @Syscall_ptr_write(ptr %r7, ptr %value)
    ; Instantiate owned variable: newCount
    %r9 = alloca i64
    %r10 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r11 = load i64, ptr %r10
    %r12 = add i64 %r11, 1
    store i64 %r12, ptr %r9
    %r13 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: get
define ptr @List_Integer_get(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r14 = alloca i64
    store i64 0, ptr %r14
    ; Instantiate owned variable: idx
    %r15 = alloca i64
    %r16 = call i64 @indextoInt64()
    store i64 %r16, ptr %r15
    ; Instantiate owned variable: offset
    %r17 = alloca i64
    %r18 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r19 = load i64, ptr %r18
    %r20 = load i64, ptr %r15
    %r21 = mul i64 %r20, 8
    %r22 = add i64 %r19, %r21
    store i64 %r22, ptr %r17
    %r23 = load i64, ptr %r17
    %r24 = call ptr @Syscall_ptr_read(ptr %r23)
    ret ptr %r24
}

; Method: set
define ptr @List_Integer_set(ptr %this, ptr %index, ptr %value) #1 {
    ; Instantiate owned variable: zero
    %r25 = alloca i64
    store i64 0, ptr %r25
    ; Instantiate owned variable: idx
    %r26 = alloca i64
    %r27 = call i64 @indextoInt64()
    store i64 %r27, ptr %r26
    ; Instantiate owned variable: offset
    %r28 = alloca i64
    %r29 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r30 = load i64, ptr %r29
    %r31 = load i64, ptr %r26
    %r32 = mul i64 %r31, 8
    %r33 = add i64 %r30, %r32
    store i64 %r33, ptr %r28
    %r34 = load i64, ptr %r28
    %r35 = call ptr @Syscall_ptr_write(ptr %r34, ptr %value)
    ret ptr null  ; implicit return
}

; Method: size
define ptr @List_Integer_size(ptr %this) #1 {
    %r36 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r37 = load i64, ptr %r36
    %r38 = call ptr @Integer_Constructor(ptr %r37)
    ret ptr %r38
}

; Method: isEmpty
define ptr @List_Integer_isEmpty(ptr %this) #1 {
    %r39 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r40 = load i64, ptr %r39
    %r41 = icmp eq i64 %r40, 0
    %r42 = call ptr @Bool_Constructor(ptr %r41)
    ret ptr %r42
}

; Method: clear
define ptr @List_Integer_clear(ptr %this) #1 {
    ; Instantiate owned variable: zero
    %r43 = alloca i64
    store i64 0, ptr %r43
    %r44 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: remove
define ptr @List_Integer_remove(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r45 = alloca i64
    store i64 0, ptr %r45
    ; Instantiate owned variable: idx
    %r46 = alloca i64
    %r47 = call i64 @indextoInt64()
    store i64 %r47, ptr %r46
    ; Instantiate owned variable: i
    %r48 = alloca i64
    %r49 = load i64, ptr %r46
    store i64 %r49, ptr %r48
    ; Instantiate owned variable: one
    %r50 = alloca i64
    store i64 1, ptr %r50
    ; Instantiate owned variable: newCount
    %r51 = alloca i64
    %r52 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r53 = load i64, ptr %r52
    %r54 = load i64, ptr %r50
    %r55 = sub i64 %r53, %r54
    store i64 %r55, ptr %r51
    %r56 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: dispose
define ptr @List_Integer_dispose(ptr %this) #1 {
    ; Instantiate owned variable: zero64
    %r57 = alloca i64
    store i64 0, ptr %r57
    %r58 = call ptr @Syscall_memcpy(i64 8)
    %r59 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}


; ============================================
; Class: MyNamespace::SomeClass_MyNamespace__MyClass
; ============================================
%class.MyNamespace::SomeClass_MyNamespace__MyClass = type { i8 }

; Method: run
define ptr @MyNamespace_SomeClass_MyNamespace__MyClass_run(ptr %this) #1 {
    ; Instantiate owned variable: myT
    %r60 = alloca ptr
    ; template parameter instantiation (not supported): T::::Constructor
    store ptr null, ptr %r60
    %r61 = load ptr, ptr %r60
    %r62 = call ptr @MyClass_getValue(ptr %r61)
    %r63 = call ptr @MyClass_add(ptr %r62, i64 53)
    %r64 = call ptr @MyClass_toString(ptr %r63)
    %r65 = call ptr @Console_printLine(ptr %r64)
    ret ptr null  ; implicit return
}


; import Language::Core
; import Language::Collections
; import Language::System
; namespace MyNamespace
; constraint MyConstraint
; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: getValue
define ptr @MyClass_getValue(ptr %this) #1 {
    %r66 = call ptr @Integer_Constructor(i64 42)
    ret ptr %r66
}


define i32 @main() #1 {
    ; Instantiate owned variable: myClass
    %r67 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r67
    ; Instantiate owned variable: testValue
    %r68 = alloca ptr
    %r69 = call ptr @Integer_Constructor(i64 42)
    store ptr %r69, ptr %r68
    ; Instantiate owned variable: testStr
    %r70 = alloca ptr
    %r71 = load ptr, ptr %r68
    %r72 = call ptr @Integer_toString(ptr %r71)
    store ptr %r72, ptr %r70
    ; Instantiate owned variable: deez
    %r73 = alloca ptr
    %r74 = call ptr @List_Integer_Constructor()
    store ptr %r74, ptr %r73
    ; Instantiate owned variable: nutz
    %r75 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r75
    %r76 = load ptr, ptr %r73
    %r77 = call ptr @Integer_Constructor(i64 5)
    %r78 = call ptr @List_Integer_add(ptr %r76, ptr %r77)
    %r79 = load ptr, ptr %r75
    %r80 = call ptr @MyNamespace_SomeClass_MyNamespace_MyClass_run(ptr %r79)
    %r81 = call ptr @String_Constructor(ptr @.str.0)
    %r82 = load ptr, ptr %r70
    %r83 = call ptr @String_append(ptr %r81, ptr %r82)
    %r84 = call ptr @Console_printLine(ptr %r83)
    ; Instantiate owned variable: num1
    %r85 = alloca ptr
    %r86 = call ptr @Integer_Constructor(i64 10)
    store ptr %r86, ptr %r85
    ; Instantiate owned variable: num2
    %r87 = alloca ptr
    %r88 = call ptr @Integer_Constructor(i64 32)
    store ptr %r88, ptr %r87
    ; Instantiate owned variable: sum
    %r89 = alloca ptr
    %r90 = load ptr, ptr %r85
    %r91 = load ptr, ptr %r87
    %r92 = call ptr @Integer_add(ptr %r90, ptr %r91)
    store ptr %r92, ptr %r89
    ; Instantiate owned variable: sumStr
    %r93 = alloca ptr
    %r94 = load ptr, ptr %r89
    %r95 = call ptr @Integer_toString(ptr %r94)
    store ptr %r95, ptr %r93
    %r96 = call ptr @String_Constructor(ptr @.str.1)
    %r97 = load ptr, ptr %r93
    %r98 = call ptr @String_append(ptr %r96, ptr %r97)
    %r99 = call ptr @Console_printLine(ptr %r98)
    %r100 = call ptr @String_Constructor(ptr @.str.2)
    %r101 = load ptr, ptr %r73
    %r102 = call ptr @Integer_Constructor(i64 0)
    %r103 = call ptr @List_Integer_get(ptr %r101, ptr %r102)
    %r104 = call ptr @List_toString(ptr %r103)
    %r105 = call ptr @String_append(ptr %r100, ptr %r104)
    %r106 = call ptr @Console_printLine(ptr %r105)
    %r107 = call ptr @String_Constructor(ptr @.str.3)
    %r108 = call ptr @Console_printLine(ptr %r107)
    ret i32 0
}
