; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [13 x i8] c"Test value: \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"Sum: \00"
@.str.2 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"
@.str.3 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"

; ============================================
; Class: List_Integer
; ============================================
%class.List_Integer = type { %class.NativeType_ptr, %class.NativeType_int64, %class.NativeType_int64 }

; Constructor for List_Integer
define ptr @List_Integer_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: add
define ptr @List_Integer_add(ptr %this, ptr %value) #1 {
    ; Instantiate owned variable: offset
    %r0 = alloca ptr
    %r1 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r2 = load %class.NativeType_ptr, ptr %r1
    %r3 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r4 = load %class.NativeType_int64, ptr %r3
    %r5 = mul i64 %r4, 8
    %r6 = add i64 %r2, %r5
    store ptr %r6, ptr %r0
    %r7 = load ptr, ptr %r0
    %r8 = call ptr @Syscall_ptr_write(ptr %r7, ptr %value)
    ; Instantiate owned variable: newCount
    %r9 = alloca ptr
    %r10 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r11 = load %class.NativeType_int64, ptr %r10
    %r12 = add i64 %r11, 1
    store ptr %r12, ptr %r9
    %r13 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: get
define ptr @List_Integer_get(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r14 = alloca ptr
    store ptr null, ptr %r14
    ; Instantiate owned variable: idx
    %r15 = alloca ptr
    %r16 = call ptr @indextoInt64()
    store ptr %r16, ptr %r15
    ; Instantiate owned variable: offset
    %r17 = alloca ptr
    %r18 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r19 = load %class.NativeType_ptr, ptr %r18
    %r20 = mul i64 %r15, 8
    %r21 = add i64 %r19, %r20
    store ptr %r21, ptr %r17
    %r22 = load ptr, ptr %r17
    %r23 = call ptr @Syscall_ptr_read(ptr %r22)
    ret ptr %r23
}

; Method: set
define ptr @List_Integer_set(ptr %this, ptr %index, ptr %value) #1 {
    ; Instantiate owned variable: zero
    %r24 = alloca ptr
    store ptr null, ptr %r24
    ; Instantiate owned variable: idx
    %r25 = alloca ptr
    %r26 = call ptr @indextoInt64()
    store ptr %r26, ptr %r25
    ; Instantiate owned variable: offset
    %r27 = alloca ptr
    %r28 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 0
    %r29 = load %class.NativeType_ptr, ptr %r28
    %r30 = mul i64 %r25, 8
    %r31 = add i64 %r29, %r30
    store ptr %r31, ptr %r27
    %r32 = load ptr, ptr %r27
    %r33 = call ptr @Syscall_ptr_write(ptr %r32, ptr %value)
    ret ptr null  ; implicit return
}

; Method: size
define ptr @List_Integer_size(ptr %this) #1 {
    %r34 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r35 = load %class.NativeType_int64, ptr %r34
    %r36 = call ptr @Integer_Constructor(ptr %r35)
    ret ptr %r36
}

; Method: isEmpty
define ptr @List_Integer_isEmpty(ptr %this) #1 {
    %r37 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r38 = load %class.NativeType_int64, ptr %r37
    %r39 = icmp eq i64 %r38, 0
    %r40 = call ptr @Bool_Constructor(ptr %r39)
    ret ptr %r40
}

; Method: clear
define ptr @List_Integer_clear(ptr %this) #1 {
    ; Instantiate owned variable: zero
    %r41 = alloca ptr
    store ptr null, ptr %r41
    %r42 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: remove
define ptr @List_Integer_remove(ptr %this, ptr %index) #1 {
    ; Instantiate owned variable: zero
    %r43 = alloca ptr
    store ptr null, ptr %r43
    ; Instantiate owned variable: idx
    %r44 = alloca ptr
    %r45 = call ptr @indextoInt64()
    store ptr %r45, ptr %r44
    ; Instantiate owned variable: i
    %r46 = alloca ptr
    store ptr %r44, ptr %r46
    ; Instantiate owned variable: one
    %r47 = alloca ptr
    store ptr 1, ptr %r47
    ; Instantiate owned variable: newCount
    %r48 = alloca ptr
    %r49 = getelementptr inbounds %class.List_Integer, ptr %this, i32 0, i32 2
    %r50 = load %class.NativeType_int64, ptr %r49
    %r51 = sub i64 %r50, %r47
    store ptr %r51, ptr %r48
    %r52 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}

; Method: dispose
define ptr @List_Integer_dispose(ptr %this) #1 {
    ; Instantiate owned variable: zero64
    %r53 = alloca ptr
    store ptr null, ptr %r53
    %r54 = call ptr @Syscall_memcpy(i64 8)
    %r55 = call ptr @Syscall_memcpy(i64 8)
    ret ptr null  ; implicit return
}


; ============================================
; Class: MyNamespace::SomeClass_MyNamespace__MyClass
; ============================================
%class.MyNamespace::SomeClass_MyNamespace__MyClass = type { i8 }

; Method: run
define ptr @MyNamespace_SomeClass_MyNamespace__MyClass_run(ptr %this) #1 {
    ; Instantiate owned variable: myT
    %r56 = alloca ptr
    ; template parameter instantiation (not supported): T::::Constructor
    store ptr null, ptr %r56
    %r57 = load ptr, ptr %r56
    %r58 = call ptr @MyClass_getValue(ptr %r57)
    %r59 = call ptr @MyClass_add(ptr %r58, i64 53)
    %r60 = call ptr @MyClass_toString(ptr %r59)
    %r61 = call ptr @Console_printLine(ptr %r60)
    ret ptr null  ; implicit return
}


; import Language::Core
; import Language::Collections
; import Language::System
; namespace MyNamespace
; constraint MyConstraint
; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: getValue
define ptr @MyClass_getValue(ptr %this) #1 {
    %r62 = call ptr @Integer_Constructor(i64 42)
    ret ptr %r62
}


define i32 @main() #1 {
    ; Instantiate owned variable: myClass
    %r63 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r63
    ; Instantiate owned variable: testValue
    %r64 = alloca ptr
    %r65 = call ptr @Integer_Constructor(i64 42)
    store ptr %r65, ptr %r64
    ; Instantiate owned variable: testStr
    %r66 = alloca ptr
    %r67 = load ptr, ptr %r64
    %r68 = call ptr @Integer_toString(ptr %r67)
    store ptr %r68, ptr %r66
    ; Instantiate owned variable: deez
    %r69 = alloca ptr
    %r70 = call ptr @List_Integer_Constructor()
    store ptr %r70, ptr %r69
    ; Instantiate owned variable: nutz
    %r71 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r71
    %r72 = load ptr, ptr %r69
    %r73 = call ptr @Integer_Constructor(i64 5)
    %r74 = call ptr @List_Integer_add(ptr %r72, ptr %r73)
    %r75 = load ptr, ptr %r71
    %r76 = call ptr @MyNamespace_SomeClass_MyNamespace_MyClass_run(ptr %r75)
    %r77 = call ptr @String_Constructor(ptr @.str.0)
    %r78 = load ptr, ptr %r66
    %r79 = call ptr @String_append(ptr %r77, ptr %r78)
    %r80 = call ptr @Console_printLine(ptr %r79)
    ; Instantiate owned variable: num1
    %r81 = alloca ptr
    %r82 = call ptr @Integer_Constructor(i64 10)
    store ptr %r82, ptr %r81
    ; Instantiate owned variable: num2
    %r83 = alloca ptr
    %r84 = call ptr @Integer_Constructor(i64 32)
    store ptr %r84, ptr %r83
    ; Instantiate owned variable: sum
    %r85 = alloca ptr
    %r86 = load ptr, ptr %r81
    %r87 = load ptr, ptr %r83
    %r88 = call ptr @Integer_add(ptr %r86, ptr %r87)
    store ptr %r88, ptr %r85
    ; Instantiate owned variable: sumStr
    %r89 = alloca ptr
    %r90 = load ptr, ptr %r85
    %r91 = call ptr @Integer_toString(ptr %r90)
    store ptr %r91, ptr %r89
    %r92 = call ptr @String_Constructor(ptr @.str.1)
    %r93 = load ptr, ptr %r89
    %r94 = call ptr @String_append(ptr %r92, ptr %r93)
    %r95 = call ptr @Console_printLine(ptr %r94)
    %r96 = call ptr @String_Constructor(ptr @.str.2)
    %r97 = load ptr, ptr %r69
    %r98 = call ptr @Integer_Constructor(i64 0)
    %r99 = call ptr @List_Integer_get(ptr %r97, ptr %r98)
    %r100 = call ptr @List_toString(ptr %r99)
    %r101 = call ptr @String_append(ptr %r96, ptr %r100)
    %r102 = call ptr @Console_printLine(ptr %r101)
    %r103 = call ptr @String_Constructor(ptr @.str.3)
    %r104 = call ptr @Console_printLine(ptr %r103)
    ret i32 0
}
