; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [23 x i8] c"Hello world from XXML!\00"

; import Language::Core
; import Language::Collections
; import Language::System
; namespace MyNamespace
; constraint MyConstraint
; ============================================
; Class: SomeClass
; Template parameters: 1
; ============================================
%class.SomeClass = type { i8 }

; Method: run
define ptr @SomeClass_run(ptr %this) #1 {
    ; Instantiate owned variable: myT
    %r0 = alloca ptr
    %r1 = call ptr @T_Constructor()
    store ptr %r1, ptr %r0
    ; complex instance method call (not yet supported)
    %r2 = call ptr @Console_printLine(i64 0)
    ret ptr null  ; implicit return
}


; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: getValue
define ptr @MyClass_getValue(ptr %this) #1 {
    %r3 = call ptr @Integer_Constructor(i64 42)
    ret ptr %r3
}


define i32 @main() #1 {
    ; Instantiate owned variable: myClass
    %r4 = alloca ptr
    ; complex instance method call (not yet supported)
    store ptr null, ptr %r4
    ; Instantiate owned variable: testValue
    %r5 = alloca ptr
    %r6 = call ptr @Integer_Constructor(i64 42)
    store ptr %r6, ptr %r5
    ; Instantiate owned variable: testStr
    %r7 = alloca ptr
    %r8 = load ptr, ptr %r5
    %r9 = call ptr @Integer_toString(ptr %r8)
    store ptr %r9, ptr %r7
    ; Instantiate owned variable: deez
    %r10 = alloca ptr
    %r11 = call ptr @List_Constructor()
    store ptr %r11, ptr %r10
    ; Instantiate owned variable: nutz
    %r12 = alloca ptr
    ; complex instance method call (not yet supported)
    store ptr null, ptr %r12
    %r13 = load ptr, ptr %r10
    %r14 = call ptr @Integer_Constructor(i64 5)
    %r15 = call ptr @List_add(ptr %r13, ptr %r14)
    %r16 = load ptr, ptr %r12
    %r17 = call ptr @SomeClass_run(ptr %r16)
    ; complex instance method call (not yet supported)
    %r18 = call ptr @Console_printLine(i64 0)
    ; Instantiate owned variable: num1
    %r19 = alloca ptr
    %r20 = call ptr @Integer_Constructor(i64 10)
    store ptr %r20, ptr %r19
    ; Instantiate owned variable: num2
    %r21 = alloca ptr
    %r22 = call ptr @Integer_Constructor(i64 32)
    store ptr %r22, ptr %r21
    ; Instantiate owned variable: sum
    %r23 = alloca ptr
    %r24 = load ptr, ptr %r19
    %r25 = call ptr @Integer_add(ptr %r24, ptr %r21)
    store ptr %r25, ptr %r23
    ; Instantiate owned variable: sumStr
    %r26 = alloca ptr
    %r27 = load ptr, ptr %r23
    %r28 = call ptr @Integer_toString(ptr %r27)
    store ptr %r28, ptr %r26
    ; complex instance method call (not yet supported)
    %r29 = call ptr @Console_printLine(i64 0)
    ; complex instance method call (not yet supported)
    %r30 = call ptr @Console_printLine(i64 0)
    %r31 = call ptr @String_Constructor(ptr @.str.0)
    %r32 = call ptr @Console_printLine(ptr %r31)
    ret i32 0
}
