; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare void @Console_print(ptr)
declare void @Console_printLine(ptr)
declare void @Console_printInt(i64)
declare void @Console_printBool(i1)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str.0 = private unnamed_addr constant [13 x i8] c"Test passed!\00"

; namespace Hello
; ============================================
; Class: MyClass
; ============================================
%class.MyClass = type { ptr }

; Constructor for MyClass
define ptr @MyClass_Constructor(ptr %this) #1 {
    ret ptr %this
}

; Method: add
define ptr @MyClass_add(ptr %this, ptr %other) #1 {
    ; Instantiate owned variable: val1
    %r0 = alloca ptr
    %r1 = call ptr @Integer_Constructor(i64 10)
    store ptr %r1, ptr %r0
    ; Instantiate owned variable: val2
    %r2 = alloca ptr
    %r3 = call ptr @Integer_Constructor(i64 20)
    store ptr %r3, ptr %r2
    ; Instantiate owned variable: sum
    %r4 = alloca ptr
    %r5 = load ptr, ptr %r0
    %r6 = load ptr, ptr %r2
    %r7 = call ptr @Integer_add(ptr %r5, ptr %r6)
    store ptr %r7, ptr %r4
    %r8 = load ptr, ptr %r4
    ret ptr %r8
}


define i32 @main() #1 {
    ; Instantiate owned variable: obj
    %r9 = alloca ptr
    ; instance method call on expression with unknown type
    store ptr null, ptr %r9
    ; Instantiate owned variable: num
    %r10 = alloca ptr
    %r11 = call ptr @Integer_Constructor(i64 5)
    store ptr %r11, ptr %r10
    ; Instantiate owned variable: result
    %r12 = alloca ptr
    %r13 = load ptr, ptr %r9
    %r14 = load ptr, ptr %r10
    %r15 = call ptr @MyClass_add(ptr %r13, ptr %r14)
    store ptr %r15, ptr %r12
    %r16 = call ptr @String_Constructor(ptr @.str.0)
    %r17 = call ptr @Console_printLine(ptr %r16)
    call void @exit(i32 0)
    ret i32 0
}
