; Generated by XXML Compiler v2.0 (LLVM IR Backend)
; Target: LLVM IR 17.0
;

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Built-in type definitions
%Integer = type { i64 }
%String = type { ptr, i64 }
%Bool = type { i1 }
%Float = type { float }
%Double = type { double }

; ============================================
; XXML LLVM Runtime Library
; ============================================

; Memory Management
declare ptr @xxml_malloc(i64)
declare void @xxml_free(ptr)
declare ptr @xxml_memcpy(ptr, ptr, i64)
declare ptr @xxml_memset(ptr, i32, i64)
declare ptr @xxml_ptr_read(ptr)
declare void @xxml_ptr_write(ptr, ptr)
declare i8 @xxml_read_byte(ptr)
declare void @xxml_write_byte(ptr, i8)

; Integer Operations
declare ptr @Integer_Constructor(i64)
declare i64 @Integer_getValue(ptr)
declare ptr @Integer_add(ptr, ptr)
declare ptr @Integer_sub(ptr, ptr)
declare ptr @Integer_mul(ptr, ptr)
declare ptr @Integer_div(ptr, ptr)
declare i1 @Integer_eq(ptr, ptr)
declare i1 @Integer_ne(ptr, ptr)
declare i1 @Integer_lt(ptr, ptr)
declare i1 @Integer_le(ptr, ptr)
declare i1 @Integer_gt(ptr, ptr)
declare i1 @Integer_ge(ptr, ptr)
declare i64 @Integer_toInt64(ptr)
declare ptr @Integer_toString(ptr)

; String Operations
declare ptr @String_Constructor(ptr)
declare ptr @String_FromCString(ptr)
declare ptr @String_toCString(ptr)
declare i64 @String_length(ptr)
declare ptr @String_concat(ptr, ptr)
declare ptr @String_append(ptr, ptr)
declare i1 @String_equals(ptr, ptr)
declare void @String_destroy(ptr)

; Bool Operations
declare ptr @Bool_Constructor(i1)
declare i1 @Bool_getValue(ptr)
declare ptr @Bool_and(ptr, ptr)
declare ptr @Bool_or(ptr, ptr)
declare ptr @Bool_not(ptr)

; None Operations
declare ptr @None_Constructor()

; List Operations
declare ptr @List_Constructor()
declare void @List_add(ptr, ptr)
declare ptr @List_get(ptr, i64)
declare i64 @List_size(ptr)

; Console I/O
declare i64 @Console_readInt()
declare ptr @Console_readLine()
declare void @Console_print(ptr)
declare void @Console_printBool(i1)
declare void @Console_printInt(i64)
declare void @Console_printLine(ptr)

; System Functions
declare void @xxml_exit(i32)
declare void @exit(i32)

; Optimization attributes
attributes #0 = { noinline nounwind optnone uwtable }
attributes #1 = { nounwind uwtable }
attributes #2 = { alwaysinline nounwind uwtable }

; ============================================
; String Literal Constants
; ============================================
@.str0 = private unnamed_addr constant [23 x i8] c"Simple arithmetic test\00"

define i32 @main() #1 {
    %r0 = call ptr @Integer_Constructor(i64 10)
    %r1 = call ptr @Integer_Constructor(i64 53)
    %r2 = call ptr @String_Constructor(ptr @.str0)
    call void @Console_printLine(ptr %r2)
    ret i32 0
}
